### ISSUE TITLE
setWidth() fails when used with setHeightToRenderWholePage()

### ISSUE THREAD

**Issue by nicekiwi** [spatie/browsershot#10]
$path  = storage_path() . '/app/screenshots/';

	$browsershot = new Spatie\Browsershot\Browsershot();
	$browsershot
		->setURL('http://www.stuff.co.nz')
		->setWidth('1280')
		->setHeightToRenderWholePage()
		->save($path . 'stuff.png');

That code will render the stuff homepage with a width of 960px, not 1280px.

**Comment by Maxeee09** [comment]
I reproduced the same issue, I think it is a PhantomJS issue.

**Comment by freekmurze** [comment]
I'm also thinking it's caused by Phantom.
