### ISSUE TITLE
Wait for page to render?

### ISSUE THREAD

**Issue by gstoa** [spatie/browsershot#100]
Are there any techniques that I should/can use to wait for the html/javascript to fully render before taking the screenshot?

Using this page as an example:  [https://finance.yahoo.com/quote/MSFT?p=MSFT](url)

and the following code

```
$url = 'https://finance.yahoo.com/quote/MSFT?p=MSFT';

$html = Browsershot::url($url)
  ->bodyHtml();
Browsershot::html($html)
  ->save('sample.png');
```

successfully saves the screenshot, but as you might guess there's lots of javascript that needs to loaded before the page is fully rendered.

I have also tried the following:
```
Browsershot::html($html)
  ->setNetworkIdleTimeout(30000)
  ->save('sample.png');
```

Any suggestions are appreciated.

**Comment by freekmurze** [comment]
Try using this method: https://github.com/spatie/browsershot#set-a-network-idle-timeout

**Comment by gstoa** [comment]
I tried up to a 30 second timeout, still no results/charts displayed.

**Comment by freekmurze** [comment]
These are the options that can be passed to `page.url` in the underlying Puppeeter instance.

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options

I suggest that you manually modify the javascript file included in this package at `bin/browser.js`. Try adding and playing around with some the parameters mentioned in the puppeteer docs.

If you find something that works for you, we'll take a look on how we can set those working options via Browsershot itself.
