### ISSUE TITLE
Load the same chrome profile again to get things cached

### ISSUE THREAD

**Issue by NassarX** [spatie/browsershot#101]
According to [puppeteer](https://github.com/GoogleChrome/puppeteer#default-runtime-settings) 

> Puppeteer creates its own Chromium user profile which it cleans up on every run.

Is there any way to load the same chrome profile again, so it should ensure that images, js & other similar things are cached.

**Comment by freekmurze** [comment]
Currently there's no way to do this. 

If the code to achieve this is relatively easy I'd accept a fully tested and documented PR.
