### ISSUE TITLE
HTTPS errors

### ISSUE THREAD

**Issue by alexpgates** [spatie/browsershot#109]
I was getting an error when trying to include non-https images in PDF renders. 

ERR_CERT_COMMON_NAME_INVALID

I noticed [this issue](https://github.com/GoogleChrome/puppeteer/issues/861) on the Puppeteer repo, and updated `browser.js` to:

```
browser = await puppeteer.launch({
     ignoreHTTPSErrors: true
});
```

This seems to have fixed the issue for me.

I'd be happy to attempt a pull request if you think it is a good idea. Thank you for a really nice package.

**Comment by freekmurze** [comment]
I'd accept a PR that adds a `ignoreHttpsErrors` to the package.
