### ISSUE TITLE
Question about transparency in screenshots

### ISSUE THREAD

**Issue by rydurham** [spatie/browsershot#110]
Hello!   Thank you for releasing this package - it is very helpful!  

I noticed in the puppeteer documentation that there is a "omitBackground" option that you can use to capture screenshots with transparent backgrounds, which might be a cool option to have available in this package. 

I am happy to create a PR for this, but I thought I might see if you had any preferences for how this could be implemented.   It seems to me that you could use one of three methods: 

1. Piggyback on the existing `showBackground()` and `hideBackground()` methods that are used for pdf rendering
2. Create a new method just for screenshots, perhaps called `omitBackground()` that would set that flag
3. Create a broader utility method, perhaps called `setOption($key, $value)` that lets you pass arbitrary options from PHP into Puppeteer;  this would be the most flexible but I suppose it might also be considered too broad. 

Any thoughts or preferences?  

Thanks again!

**Comment by freekmurze** [comment]
Let's do 1 and 3.

**Comment by freekmurze** [comment]
Closing this, feel free to send the discussed PR.

**Comment by rydurham** [comment]
Thanks!  Will do.
