### ISSUE TITLE
touch and mobile enhancement

### ISSUE THREAD

**Issue by btaens** [spatie/browsershot#113]
Could hasTouch and isMobile functionality be implemented for complete mobile snapshot emulation?
The library seems to already simply pass on a JSON string to puppeteer for functionality. With this combo and user agent switching, an accurate mobile snapshot could be generated of websites.

**Comment by freekmurze** [comment]
Submit a PR that adds this to the package. If the code is simple enough, non-breaking and well tested, I’ll consider merging it in.

**Comment by btaens** [comment]
Added pull request #114
