### ISSUE TITLE
can't install alongside spatie/laravel-link-checker

### ISSUE THREAD

**Issue by vesper8** [spatie/browsershot#116]
I already installed and am using spatie/laravel-link-checker

But then when I try to install spatie/browsershot I get these errors:

I checked and it seems spatie/crawler is a dependency of spatie/laravel-link-checker

```
Using version ^3.7 for spatie/browsershot
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/crawler 2.6.0 requires spatie/browsershot ^2.4 -> satisfiable by spatie/browsershot[2.4.0, 2.4.1] but these conflict with your requirements or minimum-stability.
    - spatie/crawler 2.6.0 requires spatie/browsershot ^2.4 -> satisfiable by spatie/browsershot[2.4.0, 2.4.1] but these conflict with your requirements or minimum-stability.
    - spatie/crawler 2.6.0 requires spatie/browsershot ^2.4 -> satisfiable by spatie/browsershot[2.4.0, 2.4.1] but these conflict with your requirements or minimum-stability.
    - Installation request for spatie/crawler (locked at 2.6.0) -> satisfiable by spatie/crawler[2.6.0].
```

**Comment by vesper8** [comment]
Ah.. I think I see what the problem is.. it seems that I already have spatie/browsershot installed since it's a dependency of laravel-link-checker. But the version that is installed by installing laravel-link-checker is locked at 2.4.1 ?

compose remove spatie/laravel-link-checker produced this
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 5 removals
  - Removing spatie/laravel-link-checker (2.2.2)
  - Removing spatie/crawler (2.6.0)
  - Removing nicmart/tree (v0.2.7)
  - Removing spatie/browsershot (2.4.1)
  - Removing spatie/phpunit-snapshot-assertions (1.1.1)
```

After removing spatie/laravel-link-checker, I reinstalled browsershot and got this

```
Using version ^3.7 for spatie/browsershot
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
    1/1:	https://codeload.github.com/spatie/browsershot/legacy.zip/6af642f4db47d3f7a72b9c74d7ab1769908ee215
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Package operations: 2 installs, 0 updates, 0 removals
  - Installing spatie/phpunit-snapshot-assertions (1.1.1): Loading from cache
  - Installing spatie/browsershot (3.7.0): Loading from cache
```

And then for kicks I tried reinstalling spatie/laravel-link-checker.. expecting it to fail

Instead it worked but installed an earlier version that complies to the constraints of browsershot

```
Using version ^2.2 for spatie/laravel-link-checker
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
    1/1:	https://codeload.github.com/spatie/crawler/legacy.zip/e3f37932d0bb72ed21edb384f8e1ad204166f1f2
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Package operations: 2 installs, 0 updates, 0 removals
  - Installing spatie/crawler (2.2.1): Loading from cache
  - Installing spatie/laravel-link-checker (2.2.2): Loading from cache
```

**Comment by freekmurze** [comment]
I'll soon update the our crawler and related packages so they use Browsershot v3.

**Comment by maartenSnow** [comment]
Can't wait for this to happen ^^

**Comment by juukie** [comment]
Would be nice @freekmurze. Anything I can help you with?

**Comment by freekmurze** [comment]
Haven't gotten around to this yet.

@juukie I'd accept a PR to spatie/crawler so that it uses Browsershot v3. Because the requirements of v2 of v3 differ so much (headless Chrome vs Puppeteer) I'm going to see this as a breaking change. So other breaking changes are allowed. Be sure to update the readme of the package as well to reflect any changes you might make. Target your PR against the`v3` branch on the crawler repo that I've just created.

After that spatie/laravel-link-checker, spatie/http-status-check and spatie/laravel-sitemap should be updated to make use of the new crawler. Because of the updated requirements on the underlying Browsershot dependency we'd best create new major versions of these packages as well. Breaking changes allowed.

Let me know if you have any questions. And though I'd highly appreciate your work on this, don't feel yourself obligated in any way.

Have fun!
