### ISSUE TITLE
UTF-8 (emoji) problem on Ubuntu / working localy on macOS

### ISSUE THREAD

**Issue by grund3g** [spatie/browsershot#117]
I'm having some trouble displaying emojis. On my mac setup it's working fine, but on my ubuntu server it only displays "[]".

Is there anything I'm missing here?

**Comment by lmartins** [comment]
@grund3g did you found a solution for this?
I'm running into a similar, although not quite identical issue as described here: https://github.com/spatie/browsershot/issues/211

**Comment by lukio3** [comment]
@lmartins did you manage to get emojis working? I imagine you need to load emojis from somewhere else e.g. https://github.com/twitter/twemoji

Wondering what you decided to do.

**Comment by lmartins** [comment]
@lukio3 I wasn't having issues with Emoji, that was @grund3g. In my case was due to Japanese content that required a compatible font file.
