### ISSUE TITLE
Class 'App\Http\Controllers\Spatie\Browsershot\Browsershot' not found

### ISSUE THREAD

**Issue by lucasvrm** [spatie/browsershot#12]
Hello there! Thanks for the great working! I am already using another package created by you: spatie/laravel-analytics... You guys are amazing!

I followed the steps showed here https://github.com/spatie/browsershot but it's not working ...
I am new to laravel, so probably this is a silly mistake... What I am doing wrong?
```
$browsershot = new Spatie\Browsershot\Browsershot();
        $browsershot
            ->setURL('http://www.arstechnica.com')
            ->setWidth('1024')
            ->setHeight('768')
            ->save('previews/arstechnica-browsershot.jpg');
```

**Comment by freekmurze** [comment]
Hi, thanks for your kind words.

Please open an issue on GitHub, others may benefit from your problem /
solution. I'll take a look this week.





Freek Van der Herten
Samberstraat 69 D
2060 Antwerpen
T:  +32 3 292 56 79
M: +32 495 84 27 91
https://spatie.be

**Comment by freekmurze** [comment]
Thanks for the kind words. Change `new Spatie\Browsershot\Browsershot()` to 'new \Spatie\Browsershot\Browsershot()` to make it work.
