### ISSUE TITLE
Dealing with lazy-loaded images

### ISSUE THREAD

**Issue by olavski** [spatie/browsershot#124]
First of all, thanks for a great library!! I've been waiting for years to be able to screenshots from PHP!

I was having problems taking full-page screenshots from long pages that was lazy-loading images.
I found one solution that works in some cases, it scrolls to the bottom of the page to trigger the loading of the images, then waits.

```javascript
await page.goto(request.url, requestOptions);

console.log("Scroll and wait...");
page.evaluate(_ => {
     window.scrollBy(0, document.body.scrollHeight);             
});
await page.waitFor( 30000 ); 

console.log(await page[request.action](request.options));
```
Even with a wait-time of 30 seconds it still hadn't loaded all the images, but when increasing the wait-time I ran into other timeouts. 
Now it scrolls from the top of the page directly to the bottom of the page.
A better solution might be to scroll down the page in stages, waiting for a bit before scrolling further.

Pages I tested on was http://www.thetimes.co.uk/ and http://www.independent.co.uk/

This isn't a complete solution to the problem I was having, but I can imagine other people are also dealing with this issue so I thought I'd put it out there. Maybe someone will know how to make this work :)

**Comment by freekmurze** [comment]
We've added a `setDelay` method that hopefully will help capturing screenshots on those sites.
