### ISSUE TITLE
networkIdleTimeout is no longer supported

### ISSUE THREAD

**Issue by jonnybarnes** [spatie/browsershot#126]
It got removed from Puppeteer a few weeks ago. See the relevant commit here:

https://github.com/GoogleChrome/puppeteer/commit/ce8a952044ef318baf3d9ff25157e41571293de5

**Comment by freekmurze** [comment]
If `deprecated` the method with a good reason message. I'll not remove it yet because people can still use that method if they use an older version of Puppeteer.
