### ISSUE TITLE
Stay on the URL for 2-5 sec

### ISSUE THREAD

**Issue by IAmMukeshKumar** [spatie/browsershot#130]
I have an animated page it takes 2-3 sec to complete the animation. I want screenshot at the end of the animation.

**Comment by olavski** [comment]
Hi,

You can try and update the code in browser.js
 like this:
```javascript
await page.goto(request.url, requestOptions);

await page.waitFor( 30000 ); 

console.log(await page[request.action](request.options));
```

This should wait 3 seconds before taking the screenshot.
See if that works. :)

**Comment by WidgetsBurritos** [comment]
@olavski Based on your recommendation here I opened a PR that adds this feature in #139, if you would like to check it out.

**Comment by freekmurze** [comment]
We'll handle this further in #139
