### ISSUE TITLE
Using sys temp folder results in error

### ISSUE THREAD

**Issue by Synchro** [spatie/browsershot#132]
I want Browsershot to store its temp files in the system tmp folder, so I do this to generate a filename:

    $tmpfile = tempnam(sys_get_temp_dir(), 'thumb_') . '.jpg';

giving a value like `/private/var/folders/ht/xx6x8mk88xjfyz001s7nn2800000gn/T/thumb_JtxCh5.jpg` on macOS. This folder exists and is writable by the user the script is running as. I pass it to Browsershot like so:

    Browsershot::url($url)
        ...
        ->format(Manipulations::FORMAT_JPG)
        ->save($tmpfile);

But this results in an error:

    Impossible to create the root directory "/var/folders/ht/xx6x8mk88xjfyz001s7nn2800000gn/T/thumb_JtxCh5.jpg"

Notice that the `/private` prefix has disappeared; on macOS, `/var` is a symlink to `/private/var`, so these two paths point to the same place, so it shouldn't be a problem. However, despite this error, it creates an empty file:

     -rw-------  1 marcus  staff     0B Nov 16 11:39 /private/var/folders/ht/xx6x8mk88xjfyz001s7nn2800000gn/T/thumb_JtxCh5

Note that it's missing the `.jpg` suffix, which is mysterious given what I found in #131.

If I provide a simple path like `./image.jpg` it seems happy, however, there is definitely something strange going on here. The `Impossible to create the root directory` message comes from [inside the `league/flysystem` package](https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Local.php#L89). It looks like it's trying (and failing) to create a folder rather than a file. I wonder if it's caused by the difference between the paths with and without the `/private` prefix.

**Comment by freekmurze** [comment]
This seems like a permission issue that is not really related to Browsershot.

**Comment by Synchro** [comment]
It's definitely not permissions, and it's definitely inside Browsershot - this works perfectly in the same script using the same path:

    file_put_contents($tempfile, 'a');

Result:

    -rw-r--r--  1 marcus  staff     1B Nov 16 13:12 /private/var/folders/ht/xx6x8mk88xjfyz001s7nn2800000gn/T/thumb_USHVoG.jpg

**Comment by Synchro** [comment]
Thanks for reopening. I can see that flysystem resolves symlinks [here](https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Local.php#L76), however, this should convert `/var` to `/private/var`, not the other way around.

I've managed to get the Browsershot test suite working locally too. It might be useful to have a package.json file so that you can just do `npm install` to set it up.

**Comment by Synchro** [comment]
This is very weird - I've discovered how to trigger the error. This works:

```php
$tmpfile = tempnam(sys_get_temp_dir(), 'thumb_') . '.jpg';
Browsershot::url($url)
    ->save($tmpfile);
```

This fails with the reported error:

```php
$tmpfile = tempnam(sys_get_temp_dir(), 'thumb_') . '.jpg';
Browsershot::url($url)
    ->background('white')
    ->save($tmpfile);
```

I've no idea why setting the background should affect the save path.

PR with a failing test case forthcoming...

**Comment by Synchro** [comment]
It fails with a slightly different error on PHP 7.0:

    1) Spatie\Browsershot\Test\BrowsershotTest::it_can_save_to_temp_dir_with_background
    mkdir(): File exists

7.1 & 7.2:

    1) Spatie\Browsershot\Test\BrowsershotTest::it_can_save_to_temp_dir_with_background
    League\Flysystem\Exception: Impossible to create the root directory "/tmp/bs_Uwploo.jpg".

**Comment by Synchro** [comment]
I've partly tracked this down. The screenshot is saved to the target path before any manipulations are applied (so it works fine if no manipulations are applied), but the manipulations try to create a cache file in a folder with the same name as the file, which will always fail. The exception is thrown in `vendor/league/glide/src/Server.php` on line 526 where it does this:

```php
            $write = $this->cache->write(
                $cachedPath,
                $this->api->run($tmp, $this->getAllParams($params))
            );
```
If you set a breakpoint there you'll see that `$sourcePath` is your filename (e.g. `bs_4fWQUy.jpg`), but `$cachedPath` contains something like `bs_4fWQUy.jpg/eb70d4355bbffecbc142a887b7c815ed`. I don't know how it gets into that situation, but at least you now have a breakpoint and a symptom! It may be a bug in glide.

**Comment by Synchro** [comment]
I'm not sure how you're using it, but the glide server only attempts to create these folders if it is set to, and you can prevent it doing so by calling `setGroupCacheInFolders(false)`. If that is set it simply uses an md5 hash as a filename in the same folder as the source image.

**Comment by freekmurze** [comment]
Thanks for you work investigating this problem. Feel free to submit a PR that fixes this.

**Comment by Synchro** [comment]
By hard-coding `$this->groupCacheInFolders = false;` into `League\Glide\Server::getCachePath()` I can get this test to pass. What I've not figured out is how to set that setting from browsershot. It probably needs doing in `Image` rather than in here as Browsershot doesn't drive glide directly.

**Comment by Synchro** [comment]
So I found how to set the `groupCacheInFolders` option from `image`. It's not possible to control it from outside (e.g. in Browsershot) because the `Server` instance is created and disposed of inside the `performManipulations` function. This change in image makes the test pass in browsershot.

**Comment by freekmurze** [comment]
Now the PR in spatie/image has been merged, this should be fixed as well. Reopen if this is still causing problems.
