### ISSUE TITLE
Loading forever when opening a website

### ISSUE THREAD

**Issue by capimichi** [spatie/browsershot#147]
Hi,
when i try to open this page: "http://www.quotidiano.net/sport/calcio/sorteggio-europa-league-2018-1.3598020", it loads forever, until i receive the timeout exception after 30000ms.

Can you help me, please?
Thankyou.

**Comment by jeffjacobsen** [comment]
I too have seen this 30000ms timeout on sites that take a long time to load.

`Error: Navigation Timeout Exceeded: 30000ms exceeded at NavigatorWatcher.waitForNavigation (/usr/lib/node_modules/puppeteer/lib/NavigatorWatcher.js:76:20)`

Is there a way to change the Navigation Timeout?  Setting  `->timeout(120)`  doesn't seem to make any difference.
