### ISSUE TITLE
chinese disorder code 

### ISSUE THREAD

**Issue by manren** [spatie/browsershot#151]
I Test Page like this
![image](https://user-images.githubusercontent.com/19370655/35003853-16788c0e-fb29-11e7-901b-849a4b3282e4.png)
but save image is
![image](https://user-images.githubusercontent.com/19370655/35003925-6715e2a6-fb29-11e7-9c89-fa5318916a83.png)
how can fix this?thanks~

**Comment by henryatman** [comment]
this not browsershot problem, it's system problem, like linux server have not chinese font or chinese font support, you should solve it by yourself
