### ISSUE TITLE
Issue with flexbox when download as PDF

### ISSUE THREAD

**Issue by michtio** [spatie/browsershot#155]
When using this package in laravel and you give the PDF view through browsershot everything seems to be fine:

<img width="762" alt="screen shot 2018-01-26 at 17 13 36" src="https://user-images.githubusercontent.com/5818021/35449188-9f83d2a2-02bc-11e8-80b9-266f9c8b48c2.png">

But when actually downloading as a PDF then it seems flexbox isn't being applied correctly ( which should work since it is using headless chrome ) see the result of the PDF parsing here:

<img width="873" alt="screen shot 2018-01-26 at 17 13 53" src="https://user-images.githubusercontent.com/5818021/35449227-bd6d71f6-02bc-11e8-8a81-83ccf3e2cdd5.png">

So this gives a totally different view as what is mentioned. The weird thing about it is, that where the image should be and you can see the red title, that is also a flex item, and that flex-item does display properly, while the listing of eg. `Medium: Wood, Bronze` is splitted onto 2 lines while both containers just contain `display: flex`

**Comment by freekmurze** [comment]
This package doesn't do any rendering itself. So this issue is not related to this package, but to Puppeteer / Headless Chrome. Open up an issue at their repo.
