### ISSUE TITLE
Is it possible to pass a Laravel view to the HTML method?

### ISSUE THREAD

**Issue by lmartins** [spatie/browsershot#159]
Hi,

I'm using this library alongside with Laravel and was wondering if it would be possible to pass a view directly into the `html` method and have that generate the file, something along these lines:

```php
        $temporaryDirectory = (new TemporaryDirectory())->create();
        $pdfPath = $temporaryDirectory->path( $organization->name . '.pdf');

        Browsershot::html( view('organizations.report', compact('organization', 'results', 'purchases')) )
            ->showBackground()
            ->margins(0, 0, 0, 0)
            ->paperSize(216, 280)
            ->savePdf($pdfPath);

        return( $pdfPath );
```
Is this possible? 
The code above does generate a PDF, however all the images are missing so I wonder is this is something that is supported.

Thanks!

**Comment by freekmurze** [comment]
I intend to keep this package framework agnostic. In your application you'll need to render your view yourself and pass the html to the `html` function.

**Comment by lmartins** [comment]
@freekmurze thanks for your feedback. 
I've tried that, by rendering the view into a variable:

```php
$html = \View::make('organizations.report', compact('organization'))->render();
```

and then pass it to Browsershot:

```php
$file = Browsershot::html( $html )
            ->showBackground()
            ->margins(0, 0, 0, 0)
            ->paperSize(216, 280)
            ->save($pdfPath);
```
Problem is images still no load on the PDF, while if I simply return the variable with the view described above I get right html, including images.

Any tips here please?

**Comment by freekmurze** [comment]
Does it work if you try making a pdf from another website with images?

**Comment by lmartins** [comment]
Yeah, I've been using it for awhile, generating the PDF from an URL. In this case I'm trying a different approach just because I need that URL to be protected under a user's session.

**Comment by lmartins** [comment]
Nevermind, this was an issue with the way I was referencing images. using the helper function solved it 
```
<img src="{{ asset('/images/logo.svg') }}" class="logo">
```
