### ISSUE TITLE
Any way to generate PDFs from a Laravel protected route?

### ISSUE THREAD

**Issue by lmartins** [spatie/browsershot#160]
Hi,

I'm building a tool that relies on Browsershot to generate some reports. Problem is the web views for those reports are protected under web guards so they are not publicly available. If I try to generate a PDF from that web view I get a login page, so I wonder if theres any way to authenticate Browsershot when generating the file, or there's another way around this use case.

Thank you!

**Comment by freekmurze** [comment]
It would probably be safer to use the `html` function to manually pass the html you want rendered to a pdf.

**Comment by robbytaylor** [comment]
Another approach you could try would be to use the excellent [URL signer](https://github.com/spatie/laravel-url-signer) to create a signed URL which you could generate the PDF from.

**Comment by lmatab** [comment]
I have been able to generate the PDF for a protected route by doing:

```
 public function downloadauth($id)
{

$order= Order::find($id);

$content= view('pdf.invoice',['order' => $order])->render();

return response()->streamDownload(function ()  use ($content){

    echo  Browsershot::html($content)
              ->pdf();

},'Order_'.$id.'.pdf',['content-Type' => 'application/pdf']);


}
```

Although the generated PDF is not considering the css classes when printing in Tailwingcss

Any thoughs?

**Comment by lmatab** [comment]
@robbytaylor  Thanks a lot for your suggestion.

It has worked just great.
