### ISSUE TITLE
V2 using PHP < 7

### ISSUE THREAD

**Issue by HansPeterOrding** [spatie/browsershot#163]
It would be great, if this library could be updated to work on PHP 5.6. Unfortunately my customer is still running 5.6 and there is no way to upgrade.

**Comment by freekmurze** [comment]
Fork this repo and invest your time to create and maintain. a PHP5.6 compatible version for your customer.

**Comment by ngekoding** [comment]
Found this issue because I need for PHP 5.6 also, and base on @freekmurze answer I try to fork and make changes to make it working with PHP 5.6.

Here you can found it:
https://github.com/ngekoding/browsershot

Thank for this awesome packages.
