### ISSUE TITLE
Support {headless: false} for Puppeteer?

### ISSUE THREAD

**Issue by theianjohnson** [spatie/browsershot#169]
I tried setting headless: false in the bin/browser.js manually, but it throws an error and I'm not sure why
```
Error Output:
================
Error: Failed to launch chrome!
```

Is there something I can do to get headful Chrome to work?

**Comment by darron1217** [comment]
You can achieve it through `->setOption('args', ['--headless=false'])`

**Comment by darron1217** [comment]
But disabling headless option will cause display not found error (on cli environment)
I suggest you to try adding `->noSandbox()` option and also check the chrome is executable.
Default path is `~/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux` and you can change it by adding `->setChromePath('/usr/bin/chromium-browser')` option

**Comment by ciprian-cimpan** [comment]
Thanks for the suggestions darron1217! I tried them both but the same error message persists.

Any idea on how to bypass this? 

`[2018-06-27 22:13:09] local.ERROR: The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/var/www/project/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"$
Exit Code: 1(General error)
Working directory: /var/www/project
Output:
================
Error Output:
================
Error: Failed to launch chrome!
[0627/221309.018874:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.`

**Comment by darron1217** [comment]
>>>
Running as root without --no-sandbox is not supported. See https://crbug.com/638180.`
>>>

Did you tried adding `->noSandbox()` option?
It is definitely related to `--no-sandbox` option!

**Comment by ciprian-cimpan** [comment]
Indeed, it was the noSandbox! 👍 
My pdf generation part was in an active laravel queue, so changes to the code didn't take effect 😞 Took me a while to notice...

Again, thanks for the tips - they saved me from extra hours of despair 😃
