### ISSUE TITLE
[RFC] Support page.click

### ISSUE THREAD

**Issue by artggd** [spatie/browsershot#174]
Hi,
Supporting [page.click](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageclickselector-options) could a great addition to browsershot. Clicking on the page is the simplest way of interacting with the page before taking a screenshot.

I'm happy to implement this feature if the RFC is approved 🙂

**Comment by freekmurze** [comment]
Please send a PR with tests and an updated readme.

**Comment by artggd** [comment]
See #176 for the PR
