### ISSUE TITLE
Font issue ! always opening only one type of font

### ISSUE THREAD

**Issue by shafimpk** [spatie/browsershot#182]
Hi,

I just started to use this package with google puppeteer as mentioned in the Readme. Everything is working fine and I love this only issue Im facing is the generated pdf's are with different font! What would be the possible issue for this? Please help. Im attaching images for your reference. Same codes but different html and pdf.
![issue-pdf](https://user-images.githubusercontent.com/13327438/38720957-4f14bd34-3f09-11e8-9c21-2f125a772aa5.png)
![issue-html](https://user-images.githubusercontent.com/13327438/38720959-512d606c-3f09-11e8-9449-6043f8ecaedf.png)

**Comment by SudoGetBeer** [comment]
Possible issues:
* Chrome doesn't know the font
* the server doesn't know the font

How did you implement the font? Did you get the correct font when using chrome?

**Comment by RyonMB** [comment]
Also try maybe to add ->waitUntilNetworkIdle() so the font can actually load :)
