### ISSUE TITLE
Setting custom header and footer html not working

### ISSUE THREAD

**Issue by andreasbakir** [spatie/browsershot#186]
Dear Spatie,

I love this package, but unfortunately I am not able to set a custom header and/or footer.

On my browsershot instance i call these functions

```
->showBrowserHeaderAndFooter()
->headerHtml($header)
->footerHtml($footer)
```

as mentioned in the Readme.

these are my footer and header variables:
```
$header = '
            <header>
                <div class="logo">
                    <img src="http://via.placeholder.com/300x100" class="img-responsive">
                </div>
                <div class="contact">
                    telefoon etc.
                </div>
            </header>
        ';

footer = '<footer>
                <span class="pageNumber"></span>
            </footer>';
```

Nevertheless the header and footer won't show up...

I also tried the following. I made a file called header.html in which I opened the html tag and all the necessary tags like head, title, meta body etc. I included a bootstrap cdn in the head. I placed the logo that should be displayed on every page of the pdf in this file.

I also made a footer.html which closes all the tags I opened in the header.html file. 

with file_get_contents I took the content of these files and put them in their respective variables called $header and $footer. And at last I have a blade file which I pre-render I get it contents and that should represent the "main content" of the pdf.

This might sound a bit confusing so here is my code:

```
$mainContent = \View::make('template.main', request()->all())->render();
$header = file_get_contents(resource_path('views/template/header.html'));
$footer = file_get_contents(resource_path('views/template/footer.html'));

return Browsershot::html($mainContent)
            ->setNodeBinary('/usr/bin/node')
            ->setNpmBinary('/usr/bin/npm')
            ->setChromePath("/usr/bin/chromium-browser")
            ->showBrowserHeaderAndFooter()
            ->headerHtml($header)
            ->footerHtml($footer)
            ->pdf();
```

I am obviously doing something wrong, but I can't find anything in the docs regarding this issue.. Hope someone can help me!

**Comment by TVke** [comment]
Hi @andreasbakir 

I just tested your code. I found that the header and footer are there, just hidden behind the main content. The best way to see them is add a `->margins(10,10,10,10)` to the chain would show them.

The second thing I found is that the formatting of the header and footer is a bit unexpected. So after you add the margin you will find a really small version of your text in the header and footer. the inline style tag is your friend at that point.

The third thing I saw is that images are not supported in the header and footer. I suggest if you want a header with an image better just remove the top margin and add it to the page content. 

Hope this helps.

greetings
Thomas

**Comment by andreasbakir** [comment]
@TVke 

That explains allot! Thank you very much, I will test your solution asap and report back :)

Hartelijk dank!

**Comment by QuentinMaypic** [comment]
Hello,
Just in case you are stuck with dynamic content and page break inside, you also can insert image in base64 in footer and header...

**Comment by andreasbakir** [comment]
@QuentinMaypic True! That's what I did to fix it :)

**Comment by JBtje** [comment]
Note to the person who reads this topic, has small header text and doesn't want to spend a day searching:
For me (win 10), the "class" on the header/footer did not work. Not even when injected via `addStyleTag`

Just add the style inline `<div style="font-size:14px;">Header</div>` and it should work...

**Comment by nbyloff** [comment]
@TVke any other suggestions if adding margins didn't work? This is my code

````
return Browsershot::html(View::make('pdf.report', $data))
				->setNodeBinary('/usr/bin/node')
				->setNpmBinary('/usr/bin/npm')
				->format('A4')
				->showBackground()
				->showBrowserHeaderAndFooter()
				->margins(20, 10, 20, 10)
				->headerHtml('')
                                //->footerHtml('<h1 style="font-size:10px; margin-left:30px;">THIS HAS SAME RESULT</h1>')
				->footerHtml(View::make('pdf.partials.footer'))
				->pdf();
````

Footer partial
````
<h1 style="font-size: 10px;color: #999; margin: 15px 0;clear:both; position: relative; top: 20px;">
  Page <span class="pageNumber"></span> of <span class="totalPages"></span>
</h1>
````

I can ctrl + f and find the footer, but only see it on the last page.

**Comment by TVke** [comment]
@nbyloff
I suggest using the most recent version of the package and if the problem still occurs opening a new issue

greetings 
Thomas

**Comment by nbyloff** [comment]
Not sure what it was, but I updated the package and redid the report, it works now. I can only imagine there was conflicting margin directives. Thanks

**Comment by bridhbinary** [comment]
Is there a way to create a 'cover page' by hiding the pageNumber / footerHtml on the first loop?

**Comment by mashood-ali63** [comment]
@QuentinMaypic In tried your solution. But, it didn't work. Can you tell me what is it that Im doing wrong here?


`$type = pathinfo($path, PATHINFO_EXTENSION);
  $data = file_get_contents($path);
  $base64 = 'data:image/' . $type . ';base64,' . base64_encode($data);
  $footerHtml ="<div style='background-image: url($base64) !important;margin-left: 39px !important;font-size: 10px;width: 
   150px'><span style='color: red'>Footer</span>test text here...</div>"
`
When I pass the same base64 variable to an <img src> the image appears but its not working as a background. Any suggestion would be appreciated. Thanks!

**Comment by mashood-ali63** [comment]
Anyone still facing issues after sending the base64 image or background color to pdf footer please add `-webkit-print-color-adjust: exact` style.
[Reference](https://stackoverflow.com/questions/49257407/cannot-add-background-color-to-header-footer-in-pdf)
