### ISSUE TITLE
For some reason Chrome did not write a file at 'location'

### ISSUE THREAD

**Issue by techtic-harshad** [spatie/browsershot#189]
In CouldNotTakeBrowsershot.php line 11:

Browsershot::url('https://google.com')->save(public_path().'/google.png');

i will try to implement this but received error, anyone please help me with that?

**Comment by SudoGetBeer** [comment]
What was the error?

**Comment by techtic-harshad** [comment]
it always through the error from CouldNotTakeBrowsershot.php and says like "For some reason Chrome did not write a file at 'location/path'"

**Comment by ciprianoprea89** [comment]
Same problem here. (OS : windows 10)

**Comment by freekmurze** [comment]
I'm not a windows user, and tbh don't keep windows compatibility in mind when creating stuff.

I'd accept a PR that fixes this and is verified to work on both windows, mac and linux systems.

**Comment by shaheenkhan401** [comment]
Hey danielsdeboer,
I am using window 10. I have used addslashes() but still getting (For some reason Chrome did not write a file at `D:\xampp\htdocs\crase\public/a.png`.) is there any other solution for this ??

**Comment by standus** [comment]
It doesnt work for me on my Windows 10. 
I see that in functon callBrowser is $this->includePath is command for linux. Then there is $binPath with /bin/browser.js but on Win platform browser.js is at another path: lib/bin/browser.js .

**Comment by colinmackinlay** [comment]
Same issue for me on Win10 (Laragon). I can see the commit that addresses the above issue is in the latest release so something else is presumably stopping Chrome writing the files. Anyone found out why?

**Comment by raana96** [comment]
Hi, I have the same problem. My operating system is Windows 10. I changed escapeshellarg() to addslashes() but again I got the same error.  Please guide me if you solve the problem. Thank you.

**Comment by ndeblauw** [comment]
Installing puppeteer locally (thus: `npm install puppeteer`) instead of globally did the trick for me. 

The only thing that I find very strange is that **it works when ran from the command line** (console command, even in tinker) but **not when the command originates from a web request** (in a controller)...

**Comment by colinmackinlay** [comment]
> Installing puppeteer locally (thus: `npm install puppeteer`) instead of globally did the trick for me [Win10, Laragon, PHP 7.4].
> 
> The only thing that I find very strange is that **it works when ran from the command line** (console command, even in tinker) but **not when the command originates from a web request** (in a controller)... The trick for getting it to work there (for me) is to queue a job that generates it. Queue workers do manage to generate the image through the job.

@ndeblauw does it work for you with a pdf output? Local install works for me only with mage formats like png or jpg

**Comment by ndeblauw** [comment]
> @ndeblauw does it work for you with a pdf output? Local install works for me only with mage formats like png or jpg
Just gave it a quick test, and yes, it works without a worry, warning or error. 

As a sidenote, I also have dompdf installed in that project, so maybe it's because of that.

**Comment by colinmackinlay** [comment]
> @ndeblauw

Thanks for checking - I have dompdf too, comes with laravel/cashier and laravel/laravel. I am using mpdf in the project at present so I guess that could be clashing although I don't see how the puppeteer script would know about it. Definitely must be something about my setup. I'll maybe try a clean install of laravel and see what happens

**Comment by anditsung** [comment]
@colinmackinlay do you use it on windows?
i have this issue on linux (prod env ). but on dev env was working fine ( mac )

**Comment by colinmackinlay** [comment]
@anditsung my dev machine is Windows and prod is Linux. It fails on both! The issue seems to be in rendering pdf. Generally I see no issues producing and saving an image file. What I want though is a way to produce and render or download a pdf of a page.

**Comment by anditsung** [comment]
@colinmackinlay looks like we have different issues. Have you try using tinker to test save the file? Mine cannot run chrome

**Comment by beitomartinez** [comment]
So, I was having the same problem (using the Laravel library)... and realized that I neved installed Puppeteer!

Instructions here: https://github.com/verumconsilium/laravel-browsershot#requirements

**Comment by dilovar-91** [comment]
Same issue but works on  tinker

**Comment by PayteR** [comment]
> Installing puppeteer locally (thus: `npm install puppeteer`) instead of globally did the trick for me [Win10, Laragon, PHP 7.4].
> 
> The only thing that I find very strange is that **it works when ran from the command line** (console command, even in tinker) but **not when the command originates from a web request** (in a controller)... The trick for getting it to work there (for me) is to queue a job that generates it. Queue workers do manage to generate the image through the job.

@ndeblauw where exactly is locally?

**Comment by dlaan07** [comment]
Hi, I know this is quite a bit late, but I still have the same problem
I need to convert a Vue.js page with TailwindCSS to a .pdf file. To do this I also use a Laravel wrapper for Browsershot: https://github.com/verumconsilium/laravel-browsershot

This is what I did to generate the .pdf:

```
use VerumConsilium\Browsershot\Facades\PDF;
return PDF::setNodeBinary('PATH %~dp0;%PATH%;')->url($urlToView)->save($path);
```

And here's the exception that I got:

```
Spatie\Browsershot\Exceptions\CouldNotTakeBrowsershot
For some reason Chrome did not write a file at <location>.pdf
```

This is my current setup:
- Windows 10
- PHP version: 7.3.28
- Laravel Framework 8.64.0

> Installing puppeteer locally (thus: `npm install puppeteer`) instead of globally did the trick for me [Win10, Laragon, PHP 7.4].
> 
> The only thing that I find very strange is that **it works when ran from the command line** (console command, even in tinker) but **not when the command originates from a web request** (in a controller)... The trick for getting it to work there (for me) is to queue a job that generates it. Queue workers do manage to generate the image through the job.

My condition is quite similar to @ndeblauw here, I can generate the pdf just fine when using Tinker. But unlike him, I can't generate the .pdf using the Laravel queue. It still spits out the same exception as when I'm using the controller. If anyone has any ideas I would be willing to try them. Thank you

**Comment by dlaan07** [comment]
> > Installing puppeteer locally (thus: `npm install puppeteer`) instead of globally did the trick for me [Win10, Laragon, PHP 7.4].
> > The only thing that I find very strange is that **it works when ran from the command line** (console command, even in tinker) but **not when the command originates from a web request** (in a controller)... The trick for getting it to work there (for me) is to queue a job that generates it. Queue workers do manage to generate the image through the job.
> 
> @ndeblauw where exactly is locally?

I believe that means in your local project folder, thus the command `npm install puppeteer` instead of `npm install puppeteer global`. You should be able to find the installed puppeteer directory in YourProjectFolder\node_modules\puppeteer

**Comment by ndeblauw** [comment]
Indeed, exactly as @dlaan07 said.
