### ISSUE TITLE
Not working with URL with %20

### ISSUE THREAD

**Issue by chitep** [spatie/browsershot#19]
It seems not working with URL's with %20.

It's working with :
->setURL('http://locusnet.be/portaal/Locus')
but not with :
->setURL('http://locusnet.be/portaal/Locus/Over%20Locus/Wie%20is%20wie/')

I get message Exception in Browsershot.php line 198:
url is invalid

**Comment by chitep** [comment]
Change line 197 of browsershot.php
if (filter_var($this->url, FILTER_VALIDATE_URL) === false) {
with
if (filter_var($this->url, FILTER_VALIDATE_URL)) {
       
and now it accepts url with %20.

**Comment by freekmurze** [comment]
This piece of code outputs "valid".
```php
$url = 'http://locusnet.be/portaal/Locus/Over%20Locus/Wie%20is%20wie/';
echo filter_var($url, FILTER_VALIDATE_URL) === false ? 'not valid' : 'valid';
```
Are you sure that's the url that makes the package throw an exception?

**Comment by freekmurze** [comment]
Reopen if you have more info regarding this issue.
