### ISSUE TITLE
Call to undefined method Spatie\Image\Manipulations::setScreenshotType()

### ISSUE THREAD

**Issue by bhattraideb** [spatie/browsershot#193]
I followed the instruction to install the package in Laravel 5.6.
Also node is already installed on my machine with ubuntu16.04. When I try to run the script, I am getting this error:  Call to undefined method Spatie\Image\Manipulations::setScreenshotType()
Also I tried with this:
```
$pathToImage = '/public/screenshots/arstechnica-browsershot.jpg';
Browsershot::url('http://www.arstechnica.com')->save($pathToImage);
```
I am getting this error:
The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/var/www/development/screenshotmaker/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"http:\/\/www.arstechnica.com","action":"screenshot","options":{"path":"\/public\/screenshots\/arstechnica-browsershot.jpg","args":[],"viewport":{"width":800,"height":600}}}'" failed. Exit Code: 1(General error) Working directory: /var/www/development/screenshotmaker/public Output: ================ Error Output: ================ Error: Failed to launch chrome! [0513/103506.021180:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received. [0513/103506.021308:FATAL:content_main_delegate.cc(57)] Check failed: false. #0 0x560d3082982c base::debug::StackTrace::StackTrace() #1 0x560d307b0290 logging::LogMessage::~LogMessage() #2 0x560d2ea60de3 content::ContentMainDelegate::TerminateForFatalInitializationError() #3 0x560d304df941 content::ContentMainRunnerImpl::Initialize() #4 0x560d304e9c12 service_manager::Main() #5 0x560d304de184 content::ContentMain() #6 0x560d346b6a39 headless::(anonymous namespace)::RunContentMain() #7 0x560d346b6ac2 headless::HeadlessBrowserMain() #8 0x560d304e6f8f headless::HeadlessShellMain() #9 0x560d2ea5f1ac ChromeMain #10 0x7f59cd159830 __libc_start_main #11 0x560d2ea5f02a _start TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md at onClose (/var/www/development/screenshotmaker/node_modules/puppeteer/lib/Launcher.js:255:14) at Interface.helper.addEventListener (/var/www/development/screenshotmaker/node_modules/puppeteer/lib/Launcher.js:244:50) at Interface.emit (events.js:185:15) at Interface.close (readline.js:379:8) at Socket.onend (readline.js:152:10) at Socket.emit (events.js:185:15) at endReadableNT (_stream_readable.js:1106:12) at process._tickCallback (internal/process/next_tick.js:114:19)

What wrong I did? I already installed puppeteer with `npm install puppeteer` command.

**Comment by shoxabbos** [comment]
I also have this problem

**Comment by darron1217** [comment]
`setScreenshotType()` function added from version 3.21.0
https://github.com/spatie/browsershot/blob/master/CHANGELOG.md#3210---2018-04-13

Please check your browsershot version

**Comment by darron1217** [comment]
node error is another error which is not related to `setScreenshotType()`
Check this thread
https://github.com/GoogleChrome/puppeteer/issues/404

I suggest you to install chrome manually
