### ISSUE TITLE
pass a cookie i.e 'jsessionid' before open a url

### ISSUE THREAD

**Issue by simon998yang** [spatie/browsershot#198]
Hi ,

Is there any way to pass a cookie i.e 'jsessionid' before open a url? this is a common solution to avoid to redirect to a login page if the url is protected.

Cheers!

**Comment by freekmurze** [comment]
I don't know if this is possible, but I'd accept a fully documented PR that adds this to the package.

**Comment by ryankilf** [comment]
I've been able to shim in cookies from a laravel request like so 
`        
$cookieArray = [];
foreach ($request->cookies as $cookieKey => $cookie) {
            $cookieArray[$cookieKey] = $cookie;
        }

        Browsershot::url($url)
            ->setExtraHttpHeaders(['Cookie' => http_build_query($cookieArray, null, '; ')])
            ->save($path);
`

I think this is certainly something that could be made nicer with a PR, but for now this should get you over the hump, @simon998yang

**Comment by simon998yang** [comment]
Thanks ryankilf.

**Comment by freekmurze** [comment]
I'd accept a PR that adds a `useCookies` function to the package. Under the hood it should call `setExtraHttpHeaders` and the parameters in the comment of @ryankilf 

The PR should be full tested and an example of how to use `useCookies` should be added to the docs.

**Comment by freekmurze** [comment]
Continued in #212...

**Comment by aFluxx** [comment]
> I've been able to shim in cookies from a laravel request like so
> 
> $cookieArray = [];
> foreach ($request->cookies as $cookieKey => $cookie) {
> $cookieArray[$cookieKey] = $cookie;
> }
> 
> ```
>     Browsershot::url($url)
>         ->setExtraHttpHeaders(['Cookie' => http_build_query($cookieArray, null, '; ')])
>         ->save($path);
> ```
> I think this is certainly something that could be made nicer with a PR, but for now this should get you over the hump, @simon998yang

Hey @ryankilf I tried implementing this bc I also have to get around a login.

This is my code:
```
public function pedigreeCapture(Request $request)
    {
        $cookieArray = [];
        foreach ($request->cookies as $cookieKey => $cookie) {
            $cookieArray[$cookieKey] = $cookie;
        }
        
        $capturePigeonID = $request->input('id');

        Browsershot::url(route('pigeon.show', ['id' => $capturePigeonID]))
                    ->setExtraHttpHeaders(['Cookie' => http_build_query($cookieArray, null, '; ')])
                    ->windowSize(1920, 1080)
                    ->save('example.jpg');
    }
```

But this doesn't seem to work, since it keeps taking screen shots from the login screen. Did I miss something?

**Comment by kishorekumarvajravel** [comment]
why UseCookies is not working ??
I have passes parameter as array also in Use Cookies
