### ISSUE TITLE
"PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` ... command node  not Found

### ISSUE THREAD

**Issue by tiriwo** [spatie/browsershot#200]
I get this error when i try to use browser shot in the server:
"PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '~/vendor/spatie/browsershot/src/../bin/browser.js'  command not found

**Comment by tiriwo** [comment]
my bad seems i need to install node in server, I am using shared hosting is there a work around for this.

**Comment by freekmurze** [comment]
Best to ask support from your hosting provider.

**Comment by beganovich** [comment]
Just want to add:
If you are having this issue under WSL2, you'll need to install the Chrome on your Linux part as well:

For Ubuntu:
```
 wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
```

```
 sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
```

```
sudo apt-get update
sudo apt-get install google-chrome-stable
```

Windows 10, WSL2, 19041 build.
