### ISSUE TITLE
broken img tag. Working with strings. 

### ISSUE THREAD

**Issue by raffobaffo** [spatie/browsershot#202]
Hello, thank you for your amazing work! 
I made soem test and, despite I'm succefully able to get screenshot from given url or to save an h1 or some other HTML tags, but when I try to use it with an <img> tag it won't load the image: 
```
 $divContent = '<img src="/png.png">';
        $imageToJpg = new Browsershot();
        $imageToJpg->html($divContent)->windowSize(640, 480)->save('test.png');
```
while if I do `return  $divContent`I can see the image. 
What I'm doing wrong? 
Edit: When I say " it won't load the image" I actually mean that an image is generated with the correct sizes, but there's the classic broken thumb sign in the top left corner. When I do the same just using `<h1>Hello</1>` it works smooth.

**Comment by freekmurze** [comment]
Try adding the domain to the url in the `src` tag.

```
 $divContent = '<img src="https://yourdomain.com/png.png">';
```

**Comment by raffobaffo** [comment]
If I do that I get:

> The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/Users/Raffaele/sites/supersquare/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"","action":"screenshot","options":{"type":"png","path":"fotoaa.png","args":[],"viewport":{"width":640,"height":480}}}'" failed. Exit Code: 1(General error) Working directory: /Users/Raffaele/sites/supersquare/public Output: ================ Error Output: ================ { Error: Protocol error (Page.navigate): Cannot navigate to invalid URL undefined at Promise (/Users/Raffaele/sites/supersquare/node_modules/puppeteer/lib/Connection.js:202:56) at new Promise (<anonymous>) at CDPSession.send (/Users/Raffaele/sites/supersquare/node_modules/puppeteer/lib/Connection.js:201:12) at navigate (/Users/Raffaele/sites/supersquare/node_modules/puppeteer/lib/Page.js:591:39) at Page.goto (/Users/Raffaele/sites/supersquare/node_modules/puppeteer/lib/Page.js:571:7) at callChrome (/Users/Raffaele/sites/supersquare/vendor/spatie/browsershot/bin/browser.js:68:20) at process._tickCallback (internal/process/next_tick.js:178:7) message: 'Protocol error (Page.navigate): Cannot navigate to invalid URL undefined' } 

I'm on localhost

**Comment by raffobaffo** [comment]
Update: 
after some research and some time spent trying, I figured out how to avoid the "Cannot navigate to invalid URL undefined at Promise " error, but I'm still unable to view the rendered img tag in the screenshot. Here is the situation, with this code: 
```
 $divContent = '<p>Before</p>
                       <img style="width:50px;height:50px;" src="http://127.0.0.1:8000/test.jpg">
                       <img style="width:50px;height:50px;" src="https://cdn.pixabay.com/photo/2013/07/12/17/47/test-pattern-152459_960_720.png">

                       <p>After</p>';
        $imageToJpg = new Browsershot();
        $imageToJpg->html( $divContent)->waitUntilNetworkIdle(false)->hideBackground()->setExtraHttpHeaders(['csrf-token' =>  csrf_token(),'charset'=>'utf-8' ])->setOption('args', ['--disable-web-security'])->setDelay('8000')->windowSize(1200, 800)->timeout(120)->save('testScreenshot.png');
```
I correctly get all the elemensts but not the img served from the localhost, if I remove waitUntilNetworkIdle(false) or I set it to TRUE,  I just gave timeouts, no matter how long I set the timeout time. 
This is the screenshot generated: 
![fotoaa](https://user-images.githubusercontent.com/37933664/42032755-ec29742c-7ada-11e8-8545-7a320295ca55.png)

And this is what I see in the browser if I return $divContent (or what I should see in the screenshot too) 
<img width="187" alt="screen shot 2018-06-28 at 13 55 35" src="https://user-images.githubusercontent.com/37933664/42032832-1cb01a74-7adb-11e8-85fe-2395be7bb58f.png">

**Comment by tomhatzer** [comment]
@raffobaffo pixabay has hotlink protection enabled, so directly including images from them within an `<img>` tag on your website won't work. For the image from 127.0.0.1:8000 I'm not quite sure what might have caused it not displaying the image. Did you try it with an image on a server you own?
