### ISSUE TITLE
evaluate function in PHP 7.0

### ISSUE THREAD

**Issue by delia-curiel** [spatie/browsershot#208]
Hi, I need to use the "evaluate" function, but I can't install the last version of the package because it requires PHP 7.1, and we have installed PHP 7.0 (and cannot update for the time being).
Is there a way to use/implement/simulate the "evaluate" function with "spatie/browsershot, version 3.20"

**Comment by freekmurze** [comment]
We don't support PHP 7.0.

Feel free to fork our code and make it PHP 7.0 compatible in your own fork.
