### ISSUE TITLE
Screenshot are not generating proper size according to HTML

### ISSUE THREAD

**Issue by opqclick** [spatie/browsershot#213]
I cannot able to take a screenshot of webpage which visible part height is like 300px but seems browsershot wlays giving me 800*600px image. I am using Browsershot::url('')->save(); Is it possible to take the screenshot of a webpage of it's actual size. fullpage() also giving me sam 800*600 px image for a 300px height site.

Will anybody help me with this issue? TIA

**Comment by tomhatzer** [comment]
Do you possibly have an example of such a website? So I can help you with that 😃

**Comment by opqclick** [comment]
Hi Tom,
Thank you so much for asking but I have already found the solution. That is about, there is an option to pass elements tag and attribute. When we give URL without any tag then it takes the screenshot with some extra blank area. but if we define that like 'body' then it take the exact size of screenshot.

Thanks,
Opu Hasnat

**Comment by opqclick** [comment]
Hi Tom,
You can close this issue now. This was not an issue anymore. My mistake.

Thanks,
Opu Hasnat
