### ISSUE TITLE
POST result screenshot

### ISSUE THREAD

**Issue by delia-curiel** [spatie/browsershot#214]
Hi, 
what would be the best way to get a screenshot of a page, that needs a previous post by ajax to get the results?   I mean, I need the screenshot of the results after executing the search, that is done by a post request

Thanks!

**Comment by freekmurze** [comment]
I don't think it possible now but I'd love a PR that adds this to the package.

API could be something like this:

```
Browsershot::url('https://example.com')->usePost([
   'name' => 'value',
])->save('example.pdf');
```

**Comment by ctf0** [comment]
a workaround could be, add a js code that reads the query string from the url & populate the search field with the text, then click the search btn ex
```js
Browsershot::url('https://example.com?search=test')
    ->click('#search-btn')
    ->setDelay(500) // just to make sure we got some results b4 saving the ss
    ->save('example.pdf')
```

**Comment by tomhatzer** [comment]
Puppeteer is not capable of doing post requests on commandline ( you have to intercept the request - have a look at https://github.com/GoogleChrome/puppeteer/issues/669 ), so the post request itself would have to happen in a separate call and the resulting HTML could be interpreted by puppeteer.
Does this sound like a sane way to implement the wanted functionality?
If so, which HTTP client library would be good for such a task? Guzzle? Plain PHP with file_get_contents() or sockets? Any preferences?

**Comment by freekmurze** [comment]
If it's easy to do, try doing it with plain PHP.

**Comment by tomhatzer** [comment]
Ok I tried to get this thing running. If anyone has some time and could look at my PR that would be great. Ideas/suggestions/improvements/fixes/... are welcome.

**Comment by delia-curiel** [comment]
Thanks everyone for your answers... I'm not very sure if what I needed require changes in the package code....
I would need something similar to what @ctf0 have answered.... I mean, the sequence of calls needed to obtain the result:
1. access url  (which will be a page with a search box)
2. set a value on the search box
3. click the search button
4. screenshot the results

**Comment by freekmurze** [comment]
There's already a PR for this: #216

@delia-curiel could you test out the code in that PR and let me know (in #216) if that works for you?

**Comment by delia-curiel** [comment]
@freekmurze Hi again, I have tested with my code and it does not return the desired results....

Here is the site I want to get the screenshot from:
https://online.austrac.gov.au/ao/public/rsregister.seam

I want to get the screenshot with the results after searching a value.
I have use the code from the PR like that:

$url = "https://online.austrac.gov.au/ao/public/rsregister.seam";
$search_code = "123"; // this returns 1 record
Browsershot::url($url)
                    ->ignoreHttpsErrors()
                    ->usePost(['AJAXREQUEST' => '_viewRoot', 
                               'remittersSearchForm' => 'remittersSearchForm',
                               'remittersSearchForm:searchCriteriaId' => $search_code,
                               'remittersSearchForm:disclaimerPanelOpenedState' => '',
                               'javax.faces.ViewState' => 'j_id2',
                               'remittersSearchForm:searchButton' => 'remittersSearchForm:searchButton'
                           ])
                     ->fullPage()
                    ->setScreenshotType('jpeg', 60)
                    ->save($pathToImage);

But it generates a non-sense screenshot

**Comment by ctf0** [comment]
btw there is https://github.com/checkly/puppeteer-recorder which might help

**Comment by tomhatzer** [comment]
Gosh I'm so stupid. I'm very sorry for my misleading PR. I should have read the code from front to back. I'm so sorry. I just understood how this whole thing works.

@delia-curiel you are right, it's basically just visiting the URL, doing the input and clicking on the button. The only thing currently missing is the "doing the input" part... I'm creating a new PR for this, as it's totally different to the one I already created.

@ctf0 Thank you very much for the recorder, that extension is pretty nice!

A link to the new PR should appear here within the next few hours.

**Comment by tomhatzer** [comment]
@delia-curiel can you please test the command from my previous post with the new files from the pull request https://github.com/spatie/browsershot/pull/220 ?

**Comment by delia-curiel** [comment]
@tomhatzer hi Tom, sorry for my late response, I couldn't answer before........  Thank you so much for everything, this is what I needed and it works perfect!!
