### ISSUE TITLE
'node' is not recognized as an internal or external command, operable program or batch file. 

### ISSUE THREAD

**Issue by adikrasimirowa** [spatie/browsershot#217]
Hello , I have installed Browsershot to Laravel the same way like in the README and when I try to do something it gives me this error.
```
The command "node "C:\xp\htdocs\staticit\vendor\spatie\browsershot\src/../bin/browser.js" "{\"url\":\"https:\/\/google.com\",\"action\":\"screenshot\",\"options\":{\"type\":\"png\",\"path\":\"C:\xp\htdocs\staticit\app\Http\Controllers\/temp\/testScreenshot.png\",\"args\":[],\"viewport\":{\"width\":800,\"height\":600}}}"" failed. Exit Code: 1(General error) Working directory: C:\xp\htdocs\staticit\public Output: ================ Error Output: ================ 'node' is not recognized as an internal or external command, operable program or batch file.
```
I have installed node modules in my Laravel project root folder and when I write node -v in my cmd it is recognized.

Ad this is my controller
```
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Browsershot\Browsershot;
use Spatie\Browsershot\Exceptions\ElementNotFound;
use Spatie\Browsershot\Exceptions\CouldNotTakeBrowsershot;
use Symfony\Component\Process\Exception\ProcessFailedException;

class BrowsershotController extends Controller
{
    //
    public function it_can_take_a_screenshot()
    {
        $targetPath = __DIR__.'/temp/testScreenshot.png';
        Browsershot::url('https://google.com')
            ->save($targetPath);
        $this->assertFileExists($targetPath);
    }
}
````

**Note: Im using Win7 , Laravel 5.7 and node ,php latest version.

**Comment by freekmurze** [comment]
The error message indicates that Node doesn't seem to be installed correctly.  I don't have any experience with installing this on Windows.

**Comment by arjayads** [comment]
Experiencing similar error. Using artisan command works but not in the controller

**Comment by archmaster01** [comment]
Hi! I am in the same boat... did you finally figured this out??

**Comment by widapraponco** [comment]
Hi! I have the same issue here, I solved it by using xampp, and node error is not showed up again

**Comment by ClausMunch** [comment]
Hey guys, 
I am also running Windows (Running Laragon).
I got it working. 

```
Route::get('/screenshot', function() {
    $pathToImage = public_path('\screenshot.png');
    Browsershot::url('http://google.com')
        ->setNodeBinary('C:/my-path-to-the-node-install/bin/nodejs/node-v12/node.exe')
        ->save($pathToImage);
    echo "<img src=\"screenshot.png\">";
});
```

**Comment by sarik-k** [comment]
> Hey guys,
> I am also running Windows (Running Laragon).
> I got it working.
> 
> In your Laravel project, you need to "npm instsall puppeteer"
> When that is installed in the local node_modules folder (in the project dir), you just set the Node binary path as a parameter:
> 
> ```
> Route::get('/screenshot', function() {
>     $pathToImage = public_path('\screenshot.png');
>     Browsershot::url('http://google.com')
>         ->setNodeBinary('C:/my-path-to-the-node-install/bin/nodejs/node-v12/node.exe')
>         ->save($pathToImage);
>     echo "<img src=\"screenshot.png\">";
> });
> ```

I also have the same setup - my node.exe is in C:\Program Files\nodejs

How can I put filepath with spaces? I tried using double quotes. ^, ` etc but nothing is working.
