### ISSUE TITLE
Render a page in its full heigh

### ISSUE THREAD

**Issue by carlcs** [spatie/browsershot#22]
It looks like it's currently not possible to render a page in its full height. `setHeightToRenderWholePage` makes phantom.js not respect the width setting any more, see https://github.com/spatie/browsershot/pull/21.

A possible solution could be to set `page.viewportSize` like so:
```
page.viewportSize = { width: ".$this->width.", height: ".($this->height == 0 ? 1 : $this->height)." };
```
 and to skip the Intervention\Image\ImageManager completely if `setHeightToRenderWholePage` was used.

Is the `$imageManager->crop()` a temporary bug fix for phantom.js not respecting the height in the `page.viewportSize` config?

**Comment by freekmurze** [comment]
That's correct, it was a temporary fix. If you can improve on this, I'd be happy to accept a PR.
