### ISSUE TITLE
chrome processes are not closing

### ISSUE THREAD

**Issue by zarasargsyan** [spatie/browsershot#230]
Hello,

I'm using html to image functionality: _Browsershot save()_. 
There are timeout errors sometimes (I've changed timeout and it's ok), but I have noticed that when I'm getting an error - there are opened chrome processes by library on server side and they are not closing. 
I have found the solution too. 
In Browsershot class, callBrowser function should be $process->clearOutput(); at line 581

        if ($process->isSuccessful()) {
            return rtrim($process->getOutput());
        }
        $process->clearOutput();

        if ($process->getExitCode() === 2) {
            throw new ElementNotFound($this->additionalOptions['selector']);
        }
I can create a pull request

**Comment by freekmurze** [comment]
Feel free to PR this! 👍
