### ISSUE TITLE
Error: Fatal error: Call to undefined method Spatie\Browsershot\Browsershot::url()

### ISSUE THREAD

**Issue by edenisn** [spatie/browsershot#239]
1) load composer with command - ```curl -sS https://getcomposer.org/installer | php```
2) then - ```mv composer.phar /usr/local/bin/composer```
3) composer init
4) composer require spatie/browsershot
5) composer install
6) create file, for example, ```test.php``` in root folder of project
```
<?php
require 'vendor/autoload.php';
use Spatie\Browsershot\Browsershot;

// an image will be saved
Browsershot::url('https://www.apple.com')
   ->FullPage()
   ->save('out1.png');
?>
```
and got error: Fatal error: Call to undefined method Spatie\Browsershot\Browsershot::url() in /path/to/my/project/test.php on line 6

composer.json:
```
{
    "name": "project/name",
    "authors": [
        {
            "name": "",
            "email": ""
        }
    ],
    "require": {
        "spatie/browsershot": "^1.9"
    }
}
```

when I use:
```
$br = new Browsershot();
$br->setUrl('https://www.apple.com')->save('out1.png')
```
it works.

**Comment by hulkur** [comment]
Tried with Browsershot 3.26.0 - no error.

**Comment by andrewteg** [comment]
As an FYI for any Google searchers... I got this trying it on PHP 5.6.
