### ISSUE TITLE
Capturing page with full height sections

### ISSUE THREAD

**Issue by nicolas-t** [spatie/browsershot#240]
Hello,

I'm trying to capture a page containing multiple sections of `height:100vw`

I created a demo page here : 
http://nicolasturlais.com/bordel/browsershot.html

Firefox gave me this : 
https://user-images.githubusercontent.com/1765930/47617820-bb46dd80-dacb-11e8-8223-0a1b3062c181.png

Browsershot gave me this : 
https://user-images.githubusercontent.com/1765930/47617881-85eebf80-dacc-11e8-9efb-799a55c8acc9.png

This bug is not directly related to browsershot and a workaround seems to exist, see here : 
https://github.com/GoogleChrome/puppeteer/issues/703#issuecomment-366041479

I have been able to use it like this : 

```php

$dimensions = Browsershot::url($url)
    ->windowSize(800, 600)
    ->evaluate("JSON.stringify({height: document.body.scrollHeight, width: document.body.scrollWidth})");

$dimensions = json_decode($dimensions);

Browsershot::url($url)
    ->windowSize(800, 600)
    ->clip(0, 0, $dimensions->width, $dimensions->height)
    ->screenshot();
```

Problem is I have to load the page 2 times (one for evaluating the other to capture)

Do you have an idea on how to improve this ?

Thanks

**Comment by luizvid** [comment]
Hello, how are you?
It's a bit late, but since this is still open, let me tell you. Have you tried the following?
`Browsershot::url($url)->select('html')->screenshot();`
It seems to work as you expected;
