### ISSUE TITLE
"Maximum execution time of 30 seconds exceeded"

### ISSUE THREAD

**Issue by aFluxx** [spatie/browsershot#241]
Hello there,

I'm trying to get Browsershot to work in a test environment.

I've just created a fresh install laravel project and ran the following commands:
```
$ composer create-project laravel/laravel BrowserShot

$ cd BrowserShot

$ composer require spatie/browsershot

$ php artisan make:controller BrowsershotController -r

$ npm install puppeteer
```

I have the following function in my BrowsershotController.php:
```
public function index()
    {
        Browsershot::url('https://google.com')->save('example.pdf');
    }
```
and my route:
```
Route::get('/', 'BrowsershotController@index');
```

But once I try to go to the index of this project I get a max exec time exceeded:
https://i.gyazo.com/e627551aa1f0b8011876681b70c3a30b.png

EDIT:
I've also tried increasing my max_execution_time:
```
; Maximum execution time of each script, in seconds
; http://php.net/max-execution-time
; Note: This directive is hardcoded to 0 for the CLI SAPI
max_execution_time=300
```
_But this is probably not the way to go about. =D_
This returned another error, now something else seems to be timing out:
https://i.gyazo.com/3f5ad26d4a1c3084bc2858a1451de929.png

What am I missing here?

Thanks in advance!

**Comment by aFluxx** [comment]
Hello there,

If anyone else is experiencing this issue and found this ticket. I managed to solve this issue.

The problem was that I was using Browsershot on Windows OS with a local XAMPP installation. This didn't seem to work.

The way I got it to work was using a vagrant box.

After using `vagrant up` to initialize the box I ran `vagrant ssh` to connect to the box. In here I ran the following commands as stated in the readme.md
```
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
sudo npm install --global --unsafe-perm puppeteer
sudo chmod -R o+rx /usr/lib/node_modules/puppeteer/.local-chromium
```

Have fun browsershotting :P

**Comment by freekmurze** [comment]
Thanks for posting your solution 👍

**Comment by Abdulrahmanh95** [comment]
@aFluxx This can be solved  by opening `httpd-xampp.conf` file and remove `SetEnv TMP "\\xampp\\tmp"` line from `<IfModule env_module>`.

But I don't know what it will affect.
