### ISSUE TITLE
Rendering PDF to browser displays binary data instead of a PDF interpretation

### ISSUE THREAD

**Issue by ImadSalimi** [spatie/browsershot#253]
Hey Spatie,

first I wanna thank you all for this package and the many others that help us while developing.

As the title mentions, I have the following code which is supposed to generate a PDF from some HTML and render it directly in the browser, but this is what I get instead (on Google Chrome):

```%PDF-1.4 %���� 1 0 obj <> endobj 2 0 obj <> stream x��݇u���?DT@���S�.��`bÆ� ���Y�r`�XԳ"p6��	%���{�����M�a�MvgK����y��d˴�|�;3�����(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(�2Qm]}?��/�7y�q/?��ɣ����2���:��(��(����Z��i�{Lz�Ē� Br��	�I�5���5�ΝtK�r*�	'_��c3�ЪZ���(��(���W��i�{�2�}l*�d IIO7�Tg���~��E�:u��ϛ\t�ՍI��REQEQ�+��Lv��C&��M��|!)#�I'�"%����,�֮��r)��(���xW��sɤ�Lz�R%)#�I'�Z�fSҗa�UQy��EW��JEQEQ#���3�J��>6�j�������uI��p��&�(QEQE��2y���t�I�fS�$kӱ~�e]җ^����7��J�@��(��(jT��˔��Lz7�j%�#�'�z`��I_t�V��afѵv�&�3KQEQE%���3�"J'��n6�JG�SOu���I_t)U'�|�Ƀ�u-\�DQEQ5ZJz?3-�t�n(IIO=Q�(��l`=��M�����%�X��(��(*1%���.Q�ɤ��)U�8��z���/```

Here's my code for reference
```php
return Browsershot::html(CertificateGenerator::for($cert->user, $project))
			->setNodeBinary('/usr/bin/node')
			->landscape()
			->select('.A4')
			->showBackground()
		    ->pdf();
```

Saving the certificate to a file works wonderfully though, but I wish you could help me with this.

**Comment by freekmurze** [comment]
Make sure you set the right headers in your response to let the browser know it's getting a PDF.

Here's how you'd do it in Laravel: https://stackoverflow.com/questions/25938294/laravel-display-a-pdf-file-in-storage-without-forcing-download

**Comment by ImadSalimi** [comment]
Thanks @freekmurze that totally skipped my mind I thought the package would directly support such response. Handled it using `return response()->file($filePath)->deleteFileAfterSend();` since I dont want to keep the files on the server.

Thanks though
