### ISSUE TITLE
Cookies not working properly

### ISSUE THREAD

**Issue by najdanovicivan** [spatie/browsershot#254]
Cookies do not work properly 

The issue happens since they are set in HTTP request headers using page.setExtraHTTPHeaders(headers)

They should be properly set using page.setCookie(...cookies) method

By setting the cookies in HTTP request they are only there in the first request so the cookies are not passed to any loaded resources and if redirection happens cookie data get completely lost

**Comment by freekmurze** [comment]
This is fixed in the latest release.
