### ISSUE TITLE
Content missing sometimes

### ISSUE THREAD

**Issue by Jam0r85** [spatie/browsershot#260]
Sometimes when loading a pdf the parts of the content are refusing to be displayed with no errors.

Returning the rendered view file.

![image 20-02-2019 at 15 29](https://user-images.githubusercontent.com/18726355/53102854-6fa9bb00-3524-11e9-9a61-4d0c45f282ba.jpg)

Returning it as a PDF.

![image 20-02-2019 at 15 29](https://user-images.githubusercontent.com/18726355/53102862-71737e80-3524-11e9-900d-3c2aa3def84b.jpg)

Please excuse the marking out but hopefully if gives you an idea..

Code as follows -

`Route::get(
    'statement/{id}', function ($id) {
    $statement = \App\Statement::find($id);

    $content = view(
        'pdf.layouts.statement', [
        'branch'    => $statement->branch,
        'statement' => $statement,
        'recipient' => $statement->recipient,
    ]
    )->render();

    //return $content;

    $pdf = \Spatie\Browsershot\Browsershot::html($content)
        ->paperSize(210, 297)
        ->pdf();

    return response($pdf)->header('Content-Type', 'application/pdf');
}
);`

This happens both locally (Mojave) and online (Digital Ocean through Forge) and doesn't matter whether i'm download or streaming, same issue.

**Comment by euneuber** [comment]
Maybe you need to wait for all resources? Add:

> ->waitUntilNetworkIdle()

before saving to PDF.

(just a guess)
