### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by davidosuna1987** [spatie/browsershot#261]
Hello, I have an issue trying to make calls to browsershot in a postcards application.

I'm having the following error:

Error Output:
================
Error: net::ERR_CONNECTION_REFUSED at (website)  at navigate (/var/www/laravel/node_modules/puppeteer/lib/Page.js:539:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/var/www/laravel/vendor/spatie/browsershot/src/../bin/browser.js' '{\"url\":\"(website)",\"action\":\"screenshot\",\"options\":{\"type\":\"jpeg\",\"path\":\"\\/var\\/www\\/laravel\\/public\\/images\\/test.jpeg\",\"quality\":100,\"args\":[\"--no-sandbox\"],\"viewport\":{\"width\":1819,\"height\":1311},\"delay\":5000}}'\" failed.

Exit Code: 1(General error)

Working directory: /var/www/laravel

Have you any idea of the reason?

I must to do 150 browsershots and maybe it can be 20 and then the error appears.

Thank you for your help!

**Comment by tnatanael** [comment]
i think the website you are trying to browsershot if rejecting too many and fast attempts of accessing it,
can you paste your full php code?

**Comment by freekmurze** [comment]
This error seems to happen on the server and it not caused by this package. Closing this for now. Feel free to continue discussing this. Ping me if you find the package is in error.
