### ISSUE TITLE
PATH Error

### ISSUE THREAD

**Issue by nam-co** [spatie/browsershot#262]
Hi, hope somebody can help me, I'm getting this error, I checked that node version is ok, in both local and forge server

Puppeteer:
On forge, I used the supplied ssh commands by Spatie
On local I installed but in "public/assets/node_modules" 
(do I need to specify the path in local? but shouldn't work on forge?)

My controller:
```php
$pdf = Browsershot::html('Hello')->showBackground()->save('hello.pdf');
return $pdf->download('hello.pdf');
```

but I'm allways getting this:

The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/Users/macbookpro/Dropbox/PROJECTS/Myproject/Myproject-L56/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"file:\/\/\/var\/tmp\/0683583001551196921\/index.html","action":"pdf","options":{"path":"hello.pdf","args":[],"viewport":{"width":800,"height":600},"displayHeaderFooter":false,"printBackground":true}}'" failed. Exit Code: 1(General error) Working directory: /Users/macbookpro/Dropbox/PROJECTS/Myproject/Myproject-L56/public Output: ================ Error Output: ================ ┌───────────────────────────────────────────────────────────────┐ │ npm update check failed │ │ Try running with sudo or get access │ │ to the local update config store via │ │ sudo chown -R $USER:$(id -gn $USER) /Users/macbookpro/.config │ └───────────────────────────────────────────────────────────────┘ internal/modules/cjs/loader.js:583 throw err; ^ Error: Cannot find module 'puppeteer' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15) at Function.Module._load (internal/modules/cjs/loader.js:507:25) 

Appreciate any help, thanks in advance

**Comment by tnatanael** [comment]
I think if you installed node modules like puppeteer in a non default dir like "myapp/node_modules", you would need to specify it in the environment like this:

export NODE_PATH='public/assets/node_modules'

**Comment by nam-co** [comment]
Hi @tnatanael , sorry I didn't get a notification for the answer, thanks
sorry, Im confused, should this be in the .env file?

Appreciate the help

**Comment by nam-co** [comment]
already fix it with just 
        ->setNodeBinary('/usr/bin/node')
        ->setNpmBinary('/usr/bin/npm')
in forge
