### ISSUE TITLE
Shows error when try to click on element with clsss name and if that class belongs to multiple elements.

### ISSUE THREAD

**Issue by hashcrypt-devs-rajkot** [spatie/browsershot#263]
It works perfect when we try click on any element with ID. It also works if we use class instead of ID but that class must belong to one element only. If we try to click with class and multiple element having that class then it shows error "Node not found...".
Even I cannot use parent class to resolve this.

**Comment by tnatanael** [comment]
Its not even documented, but its a good improvement, i would try to make a PR for this...

**Comment by danhunsaker** [comment]
You have to provide a selector that returns only one item in order to click it. This is true anywhere, even if jQuery does tend to hide that sometimes.

**Comment by tnatanael** [comment]
Just like @danhunsaker said, it's stated in puppeteer documentation, so we have, nothing to do here!

selector <string> A selector to search for element to click. If there are multiple elements satisfying the selector, the first will be clicked.

**Comment by tnatanael** [comment]
You could also try a for loop and something like this:
for($i=0,...
$selector = ".myclass:eq(".$i.")";
endfor....
