### ISSUE TITLE
Issue With function Name

### ISSUE THREAD

**Issue by ssrgspdkt** [spatie/browsershot#264]
Fatal error: Call to undefined method Spatie\Browsershot\Browsershot::url() in C:\xampp\htdocs\jtgp\browsershot\index.php on line 4

**Comment by freekmurze** [comment]
Looking at the path it seems that you're not using composer to pull in this package.

The `url` function is clearly defined: https://github.com/spatie/browsershot/blob/a71cebf7cc99a3de9af02188fa6f90aa461e3738/src/Browsershot.php#L44
