### ISSUE TITLE
The process has been signaled with signal "6".

### ISSUE THREAD

**Issue by hashcrypt-devs-rajkot** [spatie/browsershot#265]
Php - 7.1.14
Laravel version - 5.6
browsershot - 3.26.2,
node - 9.3.0,
npm - 5.5.1
![image](https://user-images.githubusercontent.com/41903434/53677700-4504f280-3cda-11e9-9318-c33a1f20c3c5.png)
It shows 'The process has been signaled with signal "6".' when I use bodyHtml() method.

**Comment by atymic** [comment]
Hi :)

Can you try logging the error and posting that here?
Maybe it's worth a PR to get the library to capture errors.


```php
protected function callBrowser(array $command)
    {
        $fullCommand = $this->getFullCommand($command);

        $process = Process::fromShellCommandline($fullCommand)->setTimeout($this->timeout);

        $process->run();

        if ($process->isSuccessful()) {
            return rtrim($process->getOutput());
        }

        $this->cleanupTemporaryOptionsFile();
        $process->clearOutput();

        if ($process->getExitCode() === 2) {
            throw new ElementNotFound($this->additionalOptions['selector']);
        }
        
        Log::debug($process->getErrorOutput());

        throw new ProcessFailedException($process);
    }
```

**Comment by turbo124** [comment]
Just continuing on with this, I am now seeing this issue after upgrading my server to PHP 7.3

The Log:: never gets hit as the function dies at $process->run();

How can we proceed to debug this?

**Comment by hashcrypt-devs-rajkot** [comment]
Yes I solved this. Actually I need to create sandbox for puppeteer and then need to make environment variable with path of sandbox puppeteer.
