### ISSUE TITLE
Legacy code?

### ISSUE THREAD

**Issue by JBtje** [spatie/browsershot#270]
https://github.com/spatie/browsershot/blob/241321f88d7f65868dbe936db910d9012aa98eaa/src/Browsershot.php#L690-L692

If $key must be of type string, it will never be of type null.
Thus, the code referenced code above shall never execute (at least not in php 7.0.0+)

https://github.com/spatie/browsershot/blob/241321f88d7f65868dbe936db910d9012aa98eaa/src/Browsershot.php#L711
The return statement is not used, and obsolete, as $array is referenced.

**Comment by freekmurze** [comment]
Feel free to submit a PR with code improvements. All tests should pass unmodified.
