### ISSUE TITLE
Do not create cached file in local directory

### ISSUE THREAD

**Issue by Inkognitoo** [spatie/browsershot#273]
After work script has generate folders .cache, .config and .pki into local project folder.

How can I transfer them to the /tmp? I use `->setOption('userDataDir', '/tmp')` but it's do not work

**Comment by atymic** [comment]
I think the correct option is `--disk-cache-dir` (though you might need both).
```php
Browsershot::html('http://example.com')
  ->addChromiumArguments([
      '--userDataDir' => '/tmp/chromedata',
      '--disk-cache-dir' => '/tmp/chromecache',
  ]);
```

You might need to create the folders first, however.

**Comment by Inkognitoo** [comment]
It's work! Thank you a lot @atymic !

**Comment by atymic** [comment]
No worries :)
