### ISSUE TITLE
OpenLayers Map?

### ISSUE THREAD

**Issue by andrewteg** [spatie/browsershot#274]
I'm not sure how to debug this or if it's just me, but I'm trying to print an OpenLayers map example and it's not printing the actual map itself but just the text on the page to PDF.  My test file is just :

require 'vendor/autoload.php';
use Spatie\Browsershot\Browsershot;
$pathToImage = 'output.pdf';
Browsershot::url('https://openlayers.org/en/latest/examples/simple.html')->save($pathToImage);
echo 'done';

This is on a Windows box as we're hoping to eventually use Browsershot with a mapserver stack (ms4w.com) but this is happening on a test Windows setup with latest Apache 2.4.38 (Win32) and PHP 7.2.16 as a module.

Thanks for any ideas/tips.

**Comment by euneuber** [comment]
It is working for me (Linux/OpenSuse 15.0, PHP 7.2.5) but I need to wait for lazy-loaded resources.

> Browsershot::url('https://openlayers.org/en/latest/examples/simple.html')
    ->waitUntilNetworkIdle()
    ->save($pathToImage);
