### ISSUE TITLE
Save image and body HTML in one command

### ISSUE THREAD

**Issue by tpavlek** [spatie/browsershot#278]
I think this might be a feature request, looking at how the code is architechted. I want to take a screenshot of a page AND get the body HTML but of the same page. The way browsershot works, that is two full setup and teardowns of the browser meaning two requests, and, potentially two different pages.

Could we make a way to chain the commands so that saving an image and dumping HTML can be done together.

**Comment by freekmurze** [comment]
If this can be achieved without complicating the code too much and it can be tested well, I'd accept a PR that adds this to the package.
