### ISSUE TITLE
Disabling Javascript

### ISSUE THREAD

**Issue by philyboysmith** [spatie/browsershot#280]
I'm increasingly coming into the issue where GDPR popups are displayed immediately and dismissDialogs() isn't proving effective.

These all seem to be loaded via javascript. Is there someway to disable javascript in puppeteer via browsershot?

Eg
```
Browsershot::url('https://www.kerrang.com/the-news/exclusive-watch-the-official-video-for-kid-bookie-and-corey-taylors-new-track/')->save('example.pdf);
```
![example](https://user-images.githubusercontent.com/144503/56284120-7cedbb00-610b-11e9-9f7f-6fba785cd669.jpg)

**Comment by atymic** [comment]
It seems that puppeteer now support disabling javascript using a flag
https://github.com/GoogleChrome/puppeteer/blob/v1.17.0/docs/api.md#pagesetjavascriptenabledenabled

I'll create a PR :)

**Comment by freekmurze** [comment]
👍
