### ISSUE TITLE
Laravel PHP => Error: Cannot find module 'puppeteer'

### ISSUE THREAD

**Issue by MusabAkram** [spatie/browsershot#281]
I'm using composer to install the package.
I ran this command :
composer require spatie/browsershot

I tried the example :
Browsershot::url('https://example.com')->save($pathToImage);

it gives this error
![image](https://user-images.githubusercontent.com/19502504/56569164-ec631f00-65d1-11e9-8c95-bad6d57a450a.png)

**Comment by freekmurze** [comment]
Please make sure you follow all install instructions: https://github.com/spatie/browsershot#requirements

**Comment by MusabAkram** [comment]
> Please make sure you follow all install instructions: https://github.com/spatie/browsershot#requirements

getting a time out now
