### ISSUE TITLE
Save Image not working => Error "Max time exceeds 60 seconds"

### ISSUE THREAD

**Issue by MusabAkram** [spatie/browsershot#282]
I saved the webpage to a pdf it worked perfectly but couldn't get the image of the webpage.
Here is what i'm doing
```
Browsershot::html(view('promoImage'))
            ->fullPage()
            ->showBackground()
            ->setOption('viewport.deviceScaleFactor', 1)
            ->save('view.png');
```
this is the screenshot of error i'm getting
![image](https://user-images.githubusercontent.com/19502504/56583202-7b802f00-65f2-11e9-8222-f3f1c48925c4.png)

**Comment by Yaminn** [comment]
@MusabAkram Did you find a fix for your issue? If so, what was it?
