### ISSUE TITLE
Feature request: pass puppeteer console events to php log

### ISSUE THREAD

**Issue by lrilling** [spatie/browsershot#284]
I recently tried to setup a Symfony project which uses Browsershot to export some PDFs on my local machine using Docker. And I ran into some troubles because on my local machine the layout was completely messed up and some images were missing. So i tried to troubleshoot everything. First Browsershot, then puppeteer and all the setup. 
And while troubleshooting Browsershot I really missed the possibility to look into the console logs of the headless browser instance, which is started by puppeteer. 

puppeteer itself has an event for this (https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-console). So maybe it is possible to pass this event to some log file, if wanted by the developer.

**Comment by freekmurze** [comment]
Feel free to send a PR with tests and an updated readme. 👍
