### ISSUE TITLE
CSS and other assets are not loaded when generating PDF

### ISSUE THREAD

**Issue by brizzo** [spatie/browsershot#288]
I am generating a PDF from a rendered blade file like so:
`Browsershot::html(view('layouts.pdf', $data))->pdf()`

The HTML contains a stylesheet:
`<link href="{{ url(mix('css/app.css')) }}" rel="stylesheet">`

On my Mac (local environment, using Laravel Valet), the PDF is generated as expected; all CSS is applied and everything looks great.

On my Ubuntu server, however, the stylesheet is ignored and the PDF is generated without styles.

I can get it to work by referencing the stylesheet using the absolute path to it on the server:
`<link href="{{ public_path(mix('css/app.css')) }}" rel="stylesheet">` or
`<link href="/absolute/path/to/laravel-project/public/css/app.css" rel="stylesheet">`, but not via its public URL.

Why is this the case? Am I missing a setting somewhere?

I can access the blade view as a webpage via the browser and everything loads as expected. It's only when generating the PDF are stylesheets, images, and other assets not loading.

It appears that only the assets on my server are the ones that do not load. Styles loaded from a CDN or other external source seem to load just fine.

Could someone please point me in the right direction or explain why the assets do not load via URLs and only work via their absolute path on the server?

**Comment by brizzo** [comment]
Of course I figured this out right after posting this. My dev server is behind basic htpasswd authorization. Adding `->setExtraHttpHeaders(['Authorization' => base64_encode('user:pass')])` fixed the issue.

**Comment by crabnky** [comment]
had the same... man, it was so simple... if someone needed there is other way:
`->authenticate('username', 'password')`

**Comment by sebastiaanluca** [comment]
Having the same issue, but it's not behind any authentication. Using `public_path(mix('css/app.css'))` seems to work though.
