### ISSUE TITLE
Taking a screenshot of page behind Auth

### ISSUE THREAD

**Issue by coding-sunshine** [spatie/browsershot#29]
I am trying to take screenshot of the dashboard, but that page is behind Auth middleware so I have to pass credentials. How can I do that??
Thanks for the help in advance :)

**Comment by freekmurze** [comment]
Did you set up your own dashboard?

**Comment by coding-sunshine** [comment]
yes, its my own dashboard, and when I remove Authentication the package is taking proper screenshot of it, but I can't remove Authentication from dashboard, so when I try to take screenshot of dashboard behind Auth, it gets redirected to the Login page which is obvious. So I wanted to know if there is a way to pass credentials to the page before calling?
Thanks

**Comment by freekmurze** [comment]
Try including the username and password in your url. (warning: probably insecure)

https://user:password@your-dashboard.com

**Comment by lukesnowden** [comment]
Something like this should be ok;

```php
Browsershot::url( route( 'some.route.name', [ $elm->id, 'encrypt' => bcrypt( env( 'APP_KEY' ) ) ] ) )
    ->setChromePath( env( 'CHROME_PATH', false ) )
    ->windowSize(2560, 1600)
    ->savePdf( base_path( $filename ) );
```

Take any middleware off the route and use the Controller construct to register the middleware  instead;

```php
public function __construct()
{
    $e = request( 'encrypt' );
    if( $e && app( 'hash' )->check( env( 'APP_KEY' ), $e ) ) {
        $this->middleware( 'auth', [ 'except' => [ 'methodNameToAccess' ] ] );
    } else {
        $this->middleware( 'auth' );
    }
}
```

**Comment by aFluxx** [comment]
Hello there,

Sorry for replying to an old issue.
But I have the same problem where I'm trying to take a screenshot of a page behind an authed route.

But I'm trying @lukesnowden answer, but I can't seem to comprehend what $elm->id means? I don't see it instantiated anywhere?

**Comment by lukesnowden** [comment]
Forget that, it was just in case your route accepts a parameter. The main thing is the second parameter which if your route doesn’t accept a parameter, it will append the url as a query parameter ‘?encrypt=blabla’
