### ISSUE TITLE
jpeg and png render correctly but pdf is completely blank

### ISSUE THREAD

**Issue by maskedjellybean** [spatie/browsershot#293]
First off, thank you for Browsershot!

I'm implementing it for a site where I need to support taking a snapshot of an html page and then downloading a generated image in either png, jpeg or pdf formats. I've found that png and jpeg work perfectly, but pdf renders completely blank. Just a white background. It does not even have the same dimensions as the png and jpeg images.

Here is the code for generating the pdf:

```
$browsershot = new Browsershot();
$browsershot::url($html_file_url)
      ->setNodeBinary($node_path)
      ->setNpmBinary($npm_path)
      ->setScreenshotType($browsershot_format)
      ->windowSize($args['width'], $args['height'])
      ->dismissDialogs()
      ->waitUntilNetworkIdle()
      ->ignoreHttpsErrors()
      ->paperSize($args['width'], $args['height'], 'px')
      ->margins(0,0,0,0)
      ->showBackground();
      ->save($img_file);
```

`$img_file` is a string such as '/files/test-image.pdf'.

There are no PHP errors in the log. As far as Browsershot is concerned it has completed successfully. 

Thanks for any help!

**Comment by rvmourik** [comment]
We are experiencing the same issue on Ubuntu 16.04 LTS, locally on MacOS we don't have this issue.
We've updated Ubuntu to use all the recent versions of node/yarn/puppeteer/browsershot.

Odd thing is that it renders images, and bullets from the bullet list (without the text). See the screenshot below:

![image](https://user-images.githubusercontent.com/6427451/58235516-41b15e00-7d41-11e9-817c-03b8034a6b19.png)

I opened the PDF in Sketch, but there isn't any text. The only thing is there is an image and paths for the bullet icons.

**Comment by maskedjellybean** [comment]
Figured out my issue! It was my fault. I was trying to be overly clever about not repeating code. The above code I posted was a simplified version of my actual code. It's what I believed the end result of a a couple if statements was. In reality I was calling `$browsershot::url($html_file_url)` and then was calling other methods on `$browsershot` depending on what the image format should be. This is evidently not how this works. Refactored the code and now jpg, png and pdf all render perfectly:

```
    if ($format == 'jpg' || $format == 'png') {
      $browsershot::url($html_file_url)
        ->setNodeBinary($node_path)
        ->setNpmBinary($npm_path)
        ->setScreenshotType($browsershot_format)
        ->windowSize($args['width'], $args['height'])
        ->dismissDialogs()
        ->waitUntilNetworkIdle()
        ->ignoreHttpsErrors()
        ->save($img_file);
    }
    elseif ($format == 'pdf') {
      $browsershot::url($html_file_url)
        ->setNodeBinary($node_path)
        ->setNpmBinary($npm_path)
        ->setScreenshotType($browsershot_format)
        ->windowSize($args['width'], $args['height'])
        ->paperSize($args['width'], $args['height'], 'px')
        ->margins(0,0,0,0)
        ->showBackground()
        ->dismissDialogs()
        ->waitUntilNetworkIdle()
        ->ignoreHttpsErrors()
        ->save($img_file);
    }
```

Sorry rvmourik, I'm going to close as I think you're having a different issue than me.
