### ISSUE TITLE
PDF renders white (images do work)

### ISSUE THREAD

**Issue by rvmourik** [spatie/browsershot#294]
Possibly related to #293, below the message from that issue.

We are experiencing the same issue on Ubuntu 16.04 LTS, locally on MacOS we don't have this issue.
We've updated Ubuntu to use all the recent versions of node/yarn/puppeteer/browsershot.

Odd thing is that it renders images, and bullets from the bullet list (without the text). See the screenshot below:

![image](https://user-images.githubusercontent.com/6427451/58235516-41b15e00-7d41-11e9-817c-03b8034a6b19.png)

I opened the PDF in Sketch, but there isn't any text. The only thing is there is an image and paths for the bullet icons.

**EDIT: I also dug into the Puppeteer repo**

https://github.com/GoogleChrome/puppeteer/issues/907#issuecomment-472334126

If i understand the way Browsershot is handling the Puppeteer command it is always presenting Puppeteer with an url. If HTML option is used through Browsershot it will create a blank html page and uses that as a "fake" url.

The comment on the Puppeteer repo is saying the exact opposite scenario, replacing the `goto` with a `setContent` call.

**Comment by Antonin-netalis** [comment]
In case anyone has the same problem and stumbles upon this issue, I managed to solve this exact same problem (except it was only happening randomly in my case) by checking two things : 
- Ensure that you are using ->waitUntilNetworkIdle() before ->savePdf($path)
- Check that your html is completely valid, it seems that invalid html can cause this.
