### ISSUE TITLE
Self signed ssl certificate - assets are not loaded

### ISSUE THREAD

**Issue by crabnky** [spatie/browsershot#298]
Hi,

I'm using self signed ssl certificate on my local machine.
When I try to generate pdf from the local web page I see assets (images, css stylesheets) are not loaded.
Is there any solution for that?

Thanks.

**Comment by atymic** [comment]
Did you set set the library to ignore https errors?
```php
Browsershot::url('https://example.com')->ignoreHttpsErrors()->save($pathToImage);
```
