### ISSUE TITLE
Google font issue

### ISSUE THREAD

**Issue by rolinbos** [spatie/browsershot#299]
When I use  this in my head:
`    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700|Noto+Serif:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oxygen+Mono" rel="stylesheet">`
And then in my stylesheet the font names and generate the pdf.
He is not showing the right font and some places he is even not showing something. 

I create so my pdf:

`        Browsershot::html(view()->make('pdf', [
            'resident'        => $resident,
            'date'            => Carbon::today()->format('d-m-Y'),
            'standings'       => stand,
            'shippingAddress' => $shippingAddress,
            'country'         => $country,
        ])->render())
            ->showBrowserHeaderAndFooter()
            ->headerHtml(' ')
            ->footerHtml(view()->make('pdf.footer')->render())
            ->margins(10, 0, 30, 0)
            ->savePdf($path);`

Does somebody now how to solve this?

Thanks!

**Comment by atymic** [comment]
It's probably not loaded when the screenshot is taken.
Can you try again with `waitUntilNetworkIdle()` on your command?

**Comment by rolinbos** [comment]
@atymic It's working, thanks!

**Comment by atymic** [comment]
No worries :)
