### ISSUE TITLE
Can't fix the page width when using the setHeightToRenderWholePage() method

### ISSUE THREAD

**Issue by yassine-khachlek** [spatie/browsershot#30]
Hi,

I have a problem using this package, can't set the width when using the setHeightToRenderWholePage() method, it's always still the default width 640, this is my code :

$browsershot = new Spatie\Browsershot\Browsershot();
$browsershot
        ->setURL($url)
        ->setWidth(1024)
        ->setQuality(80)
        ->setHeightToRenderWholePage()
        //->setBackgroundColor('#FFF') 
        ->setTimeout(10000)
        ->save($path);

Thanks an advance

**Comment by sinedoOo** [comment]
I have this problem too. Anyone could help?

**Comment by code2prog** [comment]
https://github.com/spatie/browsershot/pull/31
