### ISSUE TITLE
useCookies method forces cookie domain to match that of target URL

### ISSUE THREAD

**Issue by diggersworld** [spatie/browsershot#304]
The `useCookies` method determines the domain based on the target URL: `$domain = parse_url($this->url)['host'];`. I imagine this is fine in most cases. However, if you wish to take a snapshot of a website where cookies utilise wildcard domains this creates a problem. This method, therefore, needs to allow each cookie to specify it's domain (at least optionally).

```php
    public function useCookies(array $cookies)
    {
        if (! count($cookies)) {
            return $this;
        }

        $domain = parse_url($this->url)['host'];

        $cookies = array_map(function ($value, $name) use ($domain) {
            return compact('name', 'value', 'domain');
        }, $cookies, array_keys($cookies));

        $this->setOption('cookies', $cookies);

        return $this;
    }
```

**Comment by freekmurze** [comment]
If haven't uses cookies in combination with wildcard domains yet. That's why it currently isn't supported in the package. I'd accept a fully tested PR that adds support for this.

**Comment by diggersworld** [comment]
Would you be happy with a non-breaking change like this? If a developer needed to set up cookies for different domains they could just re-use the method.

```php
public function useCookies(array $cookies, $domain = null)
{
    // ...

    if (is_null($domain)) {
        $domain = parse_url($this->url)['host'];
    }

    // ...
}
```

**Comment by freekmurze** [comment]
Go for it!
