### ISSUE TITLE
How to download spatie/browsershot generated file into User/Downloads?

### ISSUE THREAD

**Issue by sergeynilov** [spatie/browsershot#307]
Hello!
In laravel 5.8 app I use spatie/browsershot , "^3.27"

and if I save file as 
```
        $save_to_file= 'file.pdf';
        Browsershot::html(htmlspecialchars_decode($pdf_content))
                       ->showBackground()
                       ->save($save_to_file);
```
it is downloaded and saved in /public dir of my app at my local OS

If I try to set path to ‘Downloads’ directory of my Kubuntu 18 as
```
        $save_to_file= '/home/currentuser/Downloads/file.pdf';
        Browsershot::html(htmlspecialchars_decode($pdf_content))
                       ->showBackground()
                       ->save($save_to_file);
```

I got error:
```
Symfony \ Component \ Process \ Exception \ ProcessFailedException
The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/mnt/_work_sdb8/wwwroot/lar/votes/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"file:\/\/\/tmp\/0906513001561868598\/index.html","action":"pdf","options":{"path":"\/home\/serge\/Downloads\/file.pdf","args":[],"viewport":{"width":800,"height":600},"displayHeaderFooter":false,"printBackground":true}}'" failed. Exit Code: 1(General error) Working directory: /mnt/_work_sdb8/wwwroot/lar/votes/public Output: ================ Error Output: ==============
```

1) If there is a way to download generated file into ‘Downloads’(OS independently) ?

2) I think that I can use php remove function but again how define ‘Downloads’(OS independently) directory ?

**Comment by freekmurze** [comment]
> If there is a way to download generated file into ‘Downloads’(OS independently) ?

That's not a concern of this package. `save` just saves the file to the path you specify. You're responsible for the path you specify.

**Comment by danhunsaker** [comment]
In this case, what you're trying to do is better handled by your browser than by your server. Present the file as a download, rather than trying to save it someplace outside the application's own directories.

**Comment by sergeynilov** [comment]
Yes, in my kubuntu 18 I managed to upload my file with path
```
     $save_to_file= '/home/username/Downloads/file.pdf';
     Browsershot::html(htmlspecialchars_decode($pdf_content))
         ->showBackground()
         ->save($save_to_file);

```

But to run it without error I had to run in my console :
`sudo chmod -R 777 /home/username/Downloads/`


otherwize I got error access permission

1) I wonder if there is a way to escape this error on client's OS, as I can not run
`sudo chmod -R 777 /home/username/Downloads/
`on client's site.
I search OS independently decision

2) Can you advice some Javascript/Jquery script to open "SaveAs" dialog for choosing of saving location? 
And maybe somehow to check if app has not write access to info user?

**Comment by danhunsaker** [comment]
Sure, it'll work locally if you open up your permissions like that, but that's not how web applications function - they're not meant to interact with any part of the system outside their own document root.

And you don't need to use JavaScript to download files (and in a lot of cases you simply can't, for security purposes). Just set the correct header(s) to tell the browser to download rather than display the file. You can search StackOverflow for dozens of answers to how that should be set up.

In any case, what you're trying to do here is outside the scope of this library.
