### ISSUE TITLE
Fit() not applied when using screenshot()

### ISSUE THREAD

**Issue by alphametric** [spatie/browsershot#310]
From my testing, the following code will correctly render the image at 1920 x 1080 and then resize it to 200 x 200 prior to saving the file:

```php
Browsershot::url('http://www.example.com')
-> windowSize(1920, 1080)
-> fit(Manipulations::FIT_CONTAIN, 200, 200)
-> save($pathToFile);
```

However, when using the screenshot method, the image is not resized and remains at 1920 x 1080:

```php
Browsershot::url('http://www.example.com')
-> windowSize(1920, 1080)
-> fit(Manipulations::FIT_CONTAIN, 200, 200)
-> screenshot();
```

**Comment by freekmurze** [comment]
This has been fixed in the latest version.

**Comment by alphametric** [comment]
Excellent. Thanks!
