### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by liamcharmer** [spatie/browsershot#311]
Error: net::ERR_NO_SUPPORTED_PROXIES with regards to Puppeteer when I pass a proxy over. How can I solve this?

**Comment by liamcharmer** [comment]
Just set the extra http errors with proxy-authorization and getting: 
Error: net::ERR_INVALID_ARGUMENT at

**Comment by liamcharmer** [comment]
ERR_UNEXPECTED_PROXY_AUTH also appears occasionally

**Comment by atymic** [comment]
Can you post an example of the code you are using? Does your proxy have auth?

**Comment by liamcharmer** [comment]
@atymic apologies, seems like the proxy provider I was using (Crawlera) their configuration doesn't seem to work well with the recent version of Puppeteer, so i reverted to 1.6.2 for Puppeteer and it now works!

**Comment by atymic** [comment]
No worries! Might be worth closing the issue then.
