### ISSUE TITLE
Regression introduced following fix for issue #310

### ISSUE THREAD

**Issue by alphametric** [spatie/browsershot#318]
The changes made to address the problems in issue #310, have led to another small issue. 

The screenshot is now written to disk in the root of `public` directory and is not deleted following the streaming of the resource.

See the image below for an example:

<img width="252" alt="Screenshot 2019-07-26 at 1 51 11 pm" src="https://user-images.githubusercontent.com/33156775/61952759-a2ad1a80-afac-11e9-95ef-737a3ce2e045.png">

**Comment by rubenvanassche** [comment]
Can you please check release 3.32.1? This should fix the problem

**Comment by alphametric** [comment]
It does indeed. Thanks so much!
