### ISSUE TITLE
PDF size incorrect

### ISSUE THREAD

**Issue by maskedjellybean** [spatie/browsershot#319]
I'm experiencing an issue where the height of a generated PDF is incorrect. Depending on the settings, it will either generate as a single page, with an approximately 1px sliver of white on the bottom (the PDF has a background image), or I can also get it to generate as two pages, with the second page being mostly white except for a 1px sliver of background image at the top. 

Neither of these is correct. It should generate as one page with the exact dimensions I pass to `paperSize()` and `windowSize()`. As you can see I've thrown everything at this and these are the only two results I ever get.

**Two pages with sliver of background image:**

```
$browsershot::url($html_file_url)
          ->setNodeBinary($node_path)
          ->setNpmBinary($npm_path)
          ->setNodeModulePath($node_modules_path)
          ->setScreenshotType('pdf')
          ->windowSize($args['width'], $args['height'])
          ->paperSize($args['width'], $args['height'], 'px')
          ->margins(0,0,0,0)
          ->clip(0, 0, $args['width'], $args['height'])
          ->fit(Manipulations::FIT_CONTAIN, $args['width'], $args['height'])
          ->select('#container')
          ->showBackground()
          ->dismissDialogs()
          ->waitUntilNetworkIdle()
          ->ignoreHttpsErrors()
          ->save($img_file);
```
 
<img width="337" alt="Screen Shot 2019-07-26 at 11 24 06 AM" src="https://user-images.githubusercontent.com/5596661/61973117-28729b00-af98-11e9-89e0-ade2f8483746.png">

**One page with sliver of white at bottom**

Notice that I attempt to hack the height I pass to `windowSize()` and `paperSize()` by adding 1px. This prevents the addition of the extra page but results in 1px of white at the bottom.

```
        $browsershot::url($html_file_url)
          ->setNodeBinary($node_path)
          ->setNpmBinary($npm_path)
          ->setNodeModulePath($node_modules_path)
          ->setScreenshotType('pdf')
          // Occasionally Browsershot adds an addtional page to a PDF
          // which is mostly blank except for a 1px sliver of image at the top.
          // This fixes that but not sure if this will add a 1px sliver of white to
          // bottom of some generated PDFs instead.
          ->windowSize($args['width'], $args['height'] + 1)
          ->paperSize($args['width'], $args['height'] + 1, 'px')
          ->margins(0,0,0,0)
          ->clip(0, 0, $args['width'], $args['height'])
          ->fit(Manipulations::FIT_CONTAIN, $args['width'], $args['height'])
          ->select('#container')
          ->showBackground()
          ->dismissDialogs()
          ->waitUntilNetworkIdle()
          ->ignoreHttpsErrors()
          ->save($img_file);
```

<img width="342" alt="Screen Shot 2019-07-26 at 11 25 21 AM" src="https://user-images.githubusercontent.com/5596661/61973205-67a0ec00-af98-11e9-8c66-4383d531ce90.png">

**Comment by 1stevengrant** [comment]
I have similar issues pushing straight to pdf. I try to add a `1cm` margin around the page and if I add the margin via Browsershot or via CSS, `top, left, right` margins are `1cm` but the `bottom` margin is always that bit larger

**Comment by alexpgates** [comment]
@maskedjellybean Did you ever come up with a solution to this? There are some discussions on the puppeteer repo that seem related. https://github.com/puppeteer/puppeteer/issues/2278

**Comment by maskedjellybean** [comment]
@alexpgates I wish I could help. I don't think I did figure it out and I'm no longer on the project that needed this.
