### ISSUE TITLE
Option to request interception?

### ISSUE THREAD

**Issue by liamcharmer** [spatie/browsershot#322]
Sometimes some websites, timeout due to "Navigation Timeout Exceeded: 30000ms exceeded" when using a proxy. I've set the timeout to 0 and this happens. 

I was trying to find an answer on puppeteers end and i came across this?
https://github.com/GoogleChrome/puppeteer/issues/3330#issuecomment-439696313

is this something that is possible with browsershot?

And also if there is any other fix that could get around this?

The website that im trying to reach is: 
http://www.joinhoney.com/shop/amazon (also tried with https)

**Comment by freekmurze** [comment]
Currently this is not supported in our package. I'd accept a PR with tests that add support for setting request interceptors.
