### ISSUE TITLE
Formats of PDF file is not available

### ISSUE THREAD

**Issue by ehmey786** [spatie/browsershot#325]
I want to set A4 format for my pdf which is not available in the documentation please help me.

**Comment by 1stevengrant** [comment]
does this not work?

```
Browsershot::url($this->url)
            ->paperSize("210", "297")
            ->pdf();
```

**Comment by MJunaidAhmad** [comment]
It's actually available but it is not documented yet. This is how you can use the format option
```
Browsershot::url($this->url)
            ->format("A4")
            ->pdf();
```

**Comment by MJunaidAhmad** [comment]
It's actually available but it is not documented yet. This is how you can use the format option
```
Browsershot::url($this->url)
            ->format("A4")
            ->pdf();
```
I have also created a pull request. Let's see if it is accepted or rejected. As it's my first pull request to any open source project :p

**Comment by freekmurze** [comment]
We'll handle this further in #336
