### ISSUE TITLE
Navigation failed because browser has disconnected

### ISSUE THREAD

**Issue by vuekev** [spatie/browsershot#330]
Hi,

This library has been working well as part of a Laravel 5.8 project I'm working on. However, as of today, I am suddenly seeing failures, similar to -

The command "PATH=/usr/bin NODE_PATH=`/usr/bin/node /usr/bin/npm root -g` /usr/bin/node '/var/www/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"http:\/\/www.bbc.co.uk\/","action":"screenshot","options":{"type":"png","args":["--no-sandbox","--disable-setuid-sandbox"],"viewport":{"width":800,"height":600}}}'" failed. Exit Code: 1(General error) Working directory: /var/www/public Output: ================ Error Output: ================ Error: Navigation failed because browser has disconnected! at CDPSession.LifecycleWatcher._eventListeners.helper.addEventListener 

This is now happening on every attempt. My environment -

PHP 7.2
Node v.8.16.1
NPM v.6.4.1
Puppeteer v.1.19.0
OS - Debian Stretch (Dockerised, using standard php-7.2-fpm image)

I can only think that some library behind the scenes has been 'upgraded' when I rebuilt the Docker stack, which has caused the sudden failures. Let me know if you need more information.

Thanks!

**Comment by vuekev** [comment]
Sorry - forgot to include how I'm invoking Browsershot -

        Browsershot::url('http://www.bbc.co.uk/')
            ->setOption('args', ['--no-sandbox','--disable-setuid-sandbox'])
            ->setNodeBinary('/usr/bin/node')
            ->setNpmBinary('/usr/bin/npm')
            ->setIncludePath('/usr/bin')
            ->screenshot());

**Comment by ErnestStaug** [comment]
Did you find a solution for this? I am currently experiencing same error with big HTML file.
