### ISSUE TITLE
How to handle page breaks elegantly?

### ISSUE THREAD

**Issue by tormjens** [spatie/browsershot#333]
While I know this is probably more Puppeteer-territory I'm raising this issue since some smart people in PHP-land probably have already solved this.

In my project I'm using this to generate a CV of sorts, and when the page breaks this occurs from time to time:
![Screenshot 2019-09-16 at 10 11 43](https://user-images.githubusercontent.com/3974889/64942959-b8cbae80-d86a-11e9-9f1c-61b638329a75.png)

Any ideas as to what one can do to remedy this?

Thanks for an excellent package. 💃

**Comment by weasel2k** [comment]
This works for PDF

<div style="page-break-after:always;">

**Comment by tormjens** [comment]
@weasel2k Doesn't seem to be working for me. This seems to break the page after that div?

**Comment by nicekiwi** [comment]
@weasel2k 's solution does not solve the issue.

**Comment by alex-p-ysbm** [comment]
This can be solved with `<div style="page-break-inside: avoid;">`. 
Just keep in mind the property doesn't work inside `flex`.

**Comment by nam-co** [comment]
Hi, has any body find a better solution for forcing page breaks?

I've tried with and with out screen heigh or page-break and I cant get it to work
<section style="page-break-after:always; min-height: 100vh">Page 1</section>
<div style="page-break-after:always;"></div>
<section style="page-break-after:always; min-height: 100vh">Page 2</section>

I also tried specifying the screen size
Browsershot::url('xxxxx')->emulateMedia('print')->windowSize(2480, 3508)->format('A4')->savePdf('example.pdf');

but nothing seems to work, appreciate any help

**Comment by MathieuCominity** [comment]
@freekmurze any idea on this?

**Comment by codepotato** [comment]
The css property page-break-after was deprecated in favour of 

```break-after: page;``` 

So hopefully that helps those landing on this after a google :)

**Comment by jethromay** [comment]
Thanks @codepotato solved it for me!

**Comment by codepotato** [comment]
Very welcome @jethromay

**Comment by Theodory** [comment]
I have the same issue, I am using html table to print  export PDF when breaking to the next page duplicate the table header unawareness, how can I enforce page breaking without repeating table header. @codepotato

**Comment by amihailov** [comment]
After some hours I've got working forced page breaks. I've wrapped my content in breakopoints with divs having css properties set to : 
`div.breakable {
    page-break-before : avoid;
    page-break-inside : avoid;
}`
The content inside was flex-based or tables, it worked.
