### ISSUE TITLE
The process has been signaled with signal "4".

### ISSUE THREAD

**Issue by Tguntenaar** [spatie/browsershot#334]
As soon as I call the bodyHtml() function this exception shows up. I think it has something to do with executing javascript, because the exception occurs when calling the executeJavascript function.

I already reinstalled all dependencies like puppeteer and node v10.

![process sends signal 4](https://user-images.githubusercontent.com/28901891/65241595-32220600-dae4-11e9-8ce1-45bec750371e.jpeg)

Does anybody have a clue what the problem is or what could be causing this?

**Comment by damonbakker** [comment]
I'm having the same issue now.
It seems to be come from this
https://en.wikipedia.org/wiki/Signal_(IPC)

I am running CentOS. 
The error is not very descriptive, I will come back here to post my solution if I can figure it out.

**Comment by damonbakker** [comment]
For me, turning off selinux fixed a part of it. It seems to be a permission issue with it calling the nodejs activity behind the scenes.

I could not find a permanent way to give it an exclusion through selinux but turning it off should at least fix the signal error.

Now I have this error:

```
┌──────────────────────────────────────────────────────────────┐


│                   npm update check failed                    │


│             Try running with sudo or get access              │


│             to the local update config store via             │


│ sudo chown -R $USER:$(id -gn $USER) /usr/share/httpd/.config │


└──────────────────────────────────────────────────────────────┘


```

I am not sure how I am supposed to tell browsershot to run the shell command in sudo but the sudo chown option doesn't seem to work for me.
