### ISSUE TITLE
Could not create screenshot - Line 217

### ISSUE THREAD

**Issue by stefanmahr** [spatie/browsershot#34]
Hallo!

I am trying to get a screenshot and save it to:

`public_path('browsershot.jpg')`

But I get an error in Line 217 of browsershot.php

Can anyone help me with this issues?

**Comment by al0mie** [comment]
It can be incorrect rights on folder or using the wrong binary package of phantomjs (by default there was for Linux seems)

**Comment by leedriscoll** [comment]
@stefanmahr Did you get this working after? I have the same problem.

**Comment by freekmurze** [comment]
This package includes binaries for  MacOS and Linux. If you're on Windows this package will not work.

Meanwhile PhantomJS has been abandoned, so we'll probably not put any more work in this package.

I do still accept PRs for bugfixes though.
