### ISSUE TITLE
hideBackground() doesn't seem to produce transparent background

### ISSUE THREAD

**Issue by orthosie** [spatie/browsershot#340]
I am trying to capture a webpage with transparent background. I am using something like the following. But the resulting png file uses white background instead of transparent. Is there any other options that I need to pass?

```
$browsershot = new Browsershot($url, true);
$browsershot
          ->hideBackground()
           ->save("sample.png");

```

**Comment by axelzuzek** [comment]
Same problem when creating a pdf.
