### ISSUE TITLE
Call to undefined method savePDF

### ISSUE THREAD

**Issue by ghasemaladaghlou** [spatie/browsershot#342]
Hello.This package is wonderful for save image of URLs.

But I got an error for pdf:
( ! ) Fatal error: Uncaught Error: Call to undefined method Spatie\Browsershot\Browsershot::savePDF() in C:\wamp64\www\shot\index.php on line 11.

When check the Browsershot class, many methods not found on class! For example html and savePDF and ... 
Please help us.
Thanks

**Comment by freekmurze** [comment]
Make sure the latest version of the package is installed. You can check the installed version with `composer show`.
