### ISSUE TITLE
Class name for headerHtml and footerHtml create an error on win10

### ISSUE THREAD

**Issue by WebCimes** [spatie/browsershot#343]
Hi,

When I try to create a headerHtml or footerHtml on windows 10 with some class or style inside I got an error

For example : 

All is working if I don't put any style or class :
`->footerHtml('<footer><div>hello footer</div></footer>') `

And if I put an style or class it's return an error :
`->footerHtml('<footer><div class="pageNumber">hello footer</div></footer>') `
or
`->footerHtml('<footer><div style="color:red;">hello footer</div></footer>') `

So I can't style my footer or header, or use the variable "PageNumber, etc..", maybe it's because I try on windows 10 ?

Here the error I got : 

`Fatal error: Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command "node ^"E:^\wamp64^\www^\ressources^\class^\jquery^\vendor^\spatie^\browsershot^\src/../bin/browser.js^" ^"^{^\^"url^\^":^\^"file:^\/^\/C:^\^\WINDOWS^\^\TEMP^\^\1148764078-0585836001571749698^\^\index.html^\^",^\^"action^\^":^\^"pdf^\^",^\^"options^\^":^{^\^"path^\^":^\^"example123.pdf^\^",^\^"args^\^":^[^],^\^"viewport^\^":^{^\^"width^\^":800,^\^"height^\^":600^},^\^"displayHeaderFooter^\^":true,^\^"waitUntil^\^":^\^"networkidle0^\^",^\^"format^\^":^\^"A4^\^",^\^"margin^\^":^{^\^"top^\^":^\^"20mm^\^",^\^"right^\^":^\^"20mm^\^",^\^"bottom^\^":^\^"20mm^\^",^\^"left^\^":^\^"20mm^\^"^},^\^"headerTemplate^\^":^\^"^<footer^>^<div class=^\^\^"pageNumber^\^\^"^>hello footer^<^\/div^>^<^\/footer^>^\^"^}^}^"" failed. Exit Code: 1(General error) Working directory: E:\wamp64\www Output: ================ Error Output: ================ undefined:1 {"url":"file:\/\/C:\\WINDOWS\\TEMP\\114 in E:\wamp64\www\ressources\class\jquery\vendor\spatie\browsershot\src\Browsershot.php on line 700`

Thanks

**Comment by WebCimes** [comment]
I have found the problem who create this error on windows 10, the problem come from the quote inside footerhtml and headerhtml, if we put double quote (for class or style or other) the error appens, so we need to use only simple quote like this:
` ->footerHtml("<footer><div class='pageNumber' style='color:red;'>hello footer</div></footer>") `

**Comment by bbqhax42** [comment]
This seems to be still an ongoing issue.

**Comment by spackmat** [comment]
The suggested fix from #271 is a patch for the library that isn't tested and didn't reach any release. Avoiding double quotes is a very hacky workaround.

Maybe this issue could be reopened so that the underlying escaping problem can be addressed?
