### ISSUE TITLE
Laravel on AWS EBS : ProcessFailedException

### ISSUE THREAD

**Issue by dhwlm** [spatie/browsershot#344]
I'm getting this error 

"""
The command "PATH=$PATH:/usr/local/bin NODE_PATH=`/usr/local/bin/node /usr/local/bin/npm root -g` /usr/local/bin/node '/var/app/current/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"file:\/\/\/tmp\/1163077786-0396427001571837477\/index.html","action":"pdf","options":{"path":"\/tmp\/BrowsershotOutputgbSCqT.pdf","args":["--no-sandbox"],"viewport":{"width":800,"height":600},"displayHeaderFooter":false,"margin":{"top":"0mm","right":"0mm","bottom":"0mm","left":"0mm"}}}'" failed. ◀

Exit Code: 1(General error)

Working directory: /var/app/current/public

Output:
================

Error Output:
================
/var/app/current/vendor/spatie/browsershot/bin/browser.js:5
const [, , ...args] = process.argv;
      ^
SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
"""

any help would be appreciated. 

node -v = v0.12.2
npm -v = 2.7.4

**Comment by lucasff** [comment]
Are you really using this old node and npm versions? That's the problem actually.

**Comment by arifulhb** [comment]
**My Node versions**

node: v13.5.0
npm: 6.13.4

I am also getting the error :( Can't find a single solution.

**Comment by Elkex** [comment]
Bump, I have the same problem.

Cannot seem to find a solution. I can take screenshots of external web pages without a problem, but as soon as I try to render blade views, I get this error.

**Comment by shafimpk** [comment]
I encountered the same error. Have anyone solved this yet?

**Comment by arifulhb** [comment]
@shafimpk 

This is my final block of code and its working. I've set it in Docker and running in ECS.
```
Browsershot::url($url)
            ->setNodeBinary('/usr/bin/node')
            ->setNpmBinary('/usr/bin/npm')
            ->noSandbox()
            ->ignoreHttpsErrors()
            ->setChromePath('/usr/lib/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome')
            ->showBackground()
            ->showBrowserHeaderAndFooter()
            ->margins(20, 0, 20, 0)
            ->headerHtml(view('pdf.application.header', ['application' => $this->application])->render())
            ->footerHtml(view('pdf.application.footer')->render())
            ->format('A4')
            ->waitUntilNetworkIdle()
            ->savePdf($this->applicationPath . $this->applicationFileName);
```
