### ISSUE TITLE
Temp files not deleting

### ISSUE THREAD

**Issue by zachleigh** [spatie/browsershot#345]
I just installed 3.33.0 and it seems like #318 is back. When creating a PDF, the file is saved in the public directory and not cleaned up.

**Comment by rubenvanassche** [comment]
Hi @zachleigh,

could you please provide a piece of your code creating the pdf? When I run: 

```php
Browsershot::url('https://google.com')->savePdf('example.pdf');
```

I get a example.pdf in my public folder but all temporary files are cleaned up.
