### ISSUE TITLE
Navigation timeout of 30000

### ISSUE THREAD

**Issue by Theodory** [spatie/browsershot#346]
Navigation timeout of 30000 ms exceeded at Promise.then (/var/www/html/pdftester/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21) -- ASYNC -- at Frame.<anonymous> (/var/www/html/pdftester/node_modules/puppeteer/lib/helper.js:111:15) at Page.goto (/var/www/html/pdftester/node_modules/puppeteer/lib/Page.js:675:49) at Page.<anonymous> (/var/www/html/pdftester/node_modules/puppeteer/lib/helper.js:112:23) at callChrome (/var/www/html/pdftester/vendor/spatie/browsershot/bin/browser.js:113:20) at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }

How can I fix this?

**Comment by range-of-motion** [comment]
And how did you fix this? 👀

**Comment by AndreasHerss** [comment]
@Theodory did you fix this? if so, how?  i just started receiving this, without any changes to the server, but only when adding a large amount of html? :)

**Comment by SudoGetBeer** [comment]
If someone still needs the answer:
`
        $browsershot
            ->timeout(60) // sets timeout to 60 seconds
`
