### ISSUE TITLE
Very Big Size of Pdf files

### ISSUE THREAD

**Issue by tokomeno** [spatie/browsershot#349]
Hello is any options to compress size of pdf. 
I'm generating simple text pdf files and size is quite big around 20 MB

   ```
Browsershot::url(url('/api/getpdf/' . $id))
            ->addChromiumArguments([
                'font-render-hinting' => 'none',
            ])
            ->paperSize(210, 297)
            ->showBackground()
            ->dismissDialogs()
            ->waitUntilNetworkIdle()
            ->ignoreHttpsErrors()
            ->save($filePath);

```

**Comment by selvinkuik** [comment]
@tokomeno Did you ever find a solution to this issue? I am experiencing the exact same thing

**Comment by tokomeno** [comment]
> @tokomeno Did you ever find a solution to this issue? I am experiencing the exact same thing

Unfortunately I have not and moved my pdf generation to node and have not encounter same issue yet
