### ISSUE TITLE
screenshot() not working

### ISSUE THREAD

**Issue by olpo24** [spatie/browsershot#351]
Hi,

```php
<?php
ini_set('error_reporting', E_ALL);
require __DIR__ . '/vendor/autoload.php';
use Spatie\Browsershot\Browsershot;

$image = Browsershot::url('https://google.de')
    ->noSandbox()
    ->save('test.png')
    ->screenshot();
    ?>
```

gives me an error:

> Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function screenshot() on null in /var/www/clients/client1/web3/web/test.php:9\nStack trace:\n#0 {main}\n  thrown in /var/www/clients/client1/web3/web/test.php on line 9'

The images gets created, but there is no output to the browser.

Any hints for solving this?

Best regards,
Ole

**Comment by freekmurze** [comment]
Remove `->save('test.png')` from your chain.

**Comment by olpo24** [comment]
both together doesn't work?

**Comment by Astriel** [comment]
I've got also the same problem on my side, screenshot is doing nothing excepting printing a blank page.

**Comment by fakingfantastic** [comment]
I was only seeing raw image data when I tried the code. So I worked around it by doing this...

```php
$image =  Browsershot::url($url)->screenshot();
return response($image)->header('Content-type', 'image/png');
```

Not sure if this is the intended approach (don't see any mention in the docs), but it's working so ¯\_(ツ)_/¯
