### ISSUE TITLE
permission denied even if permissions are correct

### ISSUE THREAD

**Issue by alextime** [spatie/browsershot#358]
Hi!
I tried the package on dev/local machine and it works perfectly fine! But testing it on production server I got

`Error Output:
sh: 1: /opt/node-v11.12.0-linux-x64/bin: Permission denied`

I double checked permission of /opt/node-v11.12.0-linux-x64/bin/node and it is correct (rwxrwxr-x)

I have explicitly set 
`->setNodeBinary(env('NODE_BINARY', "/usr/local/bin/node"))
->setNpmBinary(env('NPM_BINARY', "/usr/local/bin/node"))`

And if I try to call the Browsershot::save() on tinker, using my account which is able to run node and npm I get the same result.

I tried to set permission on local-chromium
`sudo chmod -R o+rx /usr/lib/node_modules/puppeteer/.local-chromium`

I tried to install puppeteer  globally and set permissions too but with the same result.

Is it possibile that php is not allowed to run a shell command? Because permissions looks like correct...

I am using Ubuntu server 18.04

**Comment by alextime** [comment]
if I try to run node -V inside thinker it works, so it is not a php exec permission issue
`shell_exec("/opt/node-v11.12.0-linux-x64/bin/node -v");`

**Comment by alextime** [comment]
here the log
`[2019-12-04 19:23:05] local.ERROR: The command "PATH=$PATH:/usr/local/bin NODE_PATH=`/opt/node-v11.12.0-linux-x64/bin /opt/node-v11.12.0-linux-x64/bin root -g` /opt/node-v11.12.0-linux-x64/bin '/var/www/test-project/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"http:\/\/evo.redelephant.it\/tests\/test-chart-test-report-pagination\/1","action":"pdf","options":{"path":"\/var\/www\/redelephant.it\/evo.redelephant.it\/webroot\/storage\/app\/public\/performed_tests\/1\/1-verla-ritchie-1575483785.pdf","args":[],"viewport":{"width":800,"height":600},"fullPage":true,"waitUntil":"networkidle0","delay":1000}}'" failed.

Exit Code: 126(Invoked command cannot execute)

Working directory: /var/www/test-project/public

Output:
================


Error Output:
================
sh: 1: /opt/node-v11.12.0-linux-x64/bin: Permission denied
sh: 1: /opt/node-v11.12.0-linux-x64/bin: Permission denied
 {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"PATH=$PATH:/usr/local/bin NODE_PATH=`/opt/node-v11.12.0-linux-x64/bin /opt/node-v11.12.0-linux-x64/bin root -g` /opt/node-v11.12.0-linux-x64/bin '/var/www/test-project/vendor/spatie/browsershot/src/../bin/browser.js' '{\"url\":\"http:\\/\\/evo.redelephant.it\\/tests\\/test-chart-test-report-pagination\\/1\",\"action\":\"pdf\",\"options\":{\"path\":\"\\/var\\/www\\/redelephant.it\\/evo.redelephant.it\\/webroot\\/storage\\/app\\/public\\/performed_tests\\/1\\/1-verla-ritchie-1575483785.pdf\",\"args\":[],\"viewport\":{\"width\":800,\"height\":600},\"fullPage\":true,\"waitUntil\":\"networkidle0\",\"delay\":1000}}'\" failed.

Exit Code: 126(Invoked command cannot execute)

Working directory: /var/www/test-project/public

Output:
================


Error Output:
================
sh: 1: /opt/node-v11.12.0-linux-x64/bin: Permission denied
sh: 1: /opt/node-v11.12.0-linux-x64/bin: Permission denied`

**Comment by RushOT** [comment]
Same problem when using node with nvm

**Comment by jerald-jacob** [comment]
I have the same issue
-bash: /home/ubuntu/bin/repo: Permission denied

**Comment by jackkemmish** [comment]
Did anyone eventually fix their issue? Mine looks relatively similar

**Comment by crazyfree** [comment]
hmmm, so what is actual problem with nvm? can any explain?
