### ISSUE TITLE
Use another terminal instead of powershell in windows?

### ISSUE THREAD

**Issue by AlbertMulaki** [spatie/browsershot#359]
Hello! I am having problems executing the browsershot directly from controller like this in a windows environment:

```
$browserShot = Browsershot::url($url);
``` 

And i receive an error when i execute it via the postman or via chrome.

```
 "message": "The process \"node ^\"C:^\\xampp^\\htdocs^\\cuta^\\vendor^\\spatie^\\browsershot^\\src/../bin/browser.js^\" ^\"^{^\\^\"url^\\^\":^\\^\"https:^\\/^\\/ec.europa.eu^\\/taxation_customs^\\/dds2^\\/ebti^\\/ebti_consultation.jsp^?Lang=en^&Lang=en^&refcountry=^&reference=DE20777^%2F17-1^&valstartdate=^&valstartdateto=^&valenddate=^&valenddateto=^&suppldate=^&nomenc=^&nomencto=^&keywordsearch1=^&keywordsearch=^&specialkeyword=^&keywordmatchrule=OR^&descript=^&orderby=0^&Expand=true^&offset=1^&viewVal=^&isVisitedRef=false^&allRecords=0^&showProgressBar=true^\\^\",^\\^\"action^\\^\":^\\^\"content^\\^\",^\\^\"options^\\^\":^{^\\^\"args^\\^\":^[^],^\\^\"viewport^\\^\":^{^\\^\"width^\\^\":800,^\\^\"height^\\^\":600^}^}^}^\"\" exceeded the timeout of 60 seconds.",
    "exception": "Symfony\\Component\\Process\\Exception\\ProcessTimedOutException",
    "file": "C:\\xampp\\htdocs\\cuta\\vendor\\symfony\\process\\Process.php",
```

But not if i put all of this in a queue, and execute it from laravel app via `php artisan queue:listen`, It seems to work perfectly. 

I tried to execute the command manually 
```
node ^"C:^\xampp^\htdocs^\cuta^\vendor^\spatie^\browsershot^\src/../bin/browser.js^" ^"^{^\^"url^\^":^\^"https:^\/^\/ec.europa.eu^\/taxation_customs^\/dds2^\/ebti^\/ebti_consultation.jsp^?Lang=en^&Lang=en^&refcountry=^&reference=DE20777^%2F17-1^&valstartdate=^&valstartdateto=^&valenddate=^&valenddateto=^&suppldate=^&nomenc=^&nomencto=^&keywordsearch1=^&keywordsearch=^&specialkeyword=^&keywordmatchrule=OR^&descript=^&orderby=0^&Expand=true^&offset=1^&viewVal=^&isVisitedRef=false^&allRecords=0^&showProgressBar=true^\^",^\^"action^\^":^\^"content^\^",^\^"options^\^":^{^\^"args^\^":^[^],^\^"viewport^\^":^{^\^"width^\^":800,^\^"height^\^":600^}^}^}^"
``` 

In powershell it fails, and in other terminals like git bash, or cmd, it works correctly.

Does anyone have any idea how can i tell browsershot to use another terminal? 
Or any kind of help is really appreciated.

Thanks in advance.

**Comment by maltonite** [comment]
I am getting a similar issue on windows 10, works from git cmd but not from the controller.

The error I am getting is:

`
The command "node ^"~\vendor^\spatie^\browsershot^\src/../bin/browser.js^" ^"^{^\^"url^\^":^\^"https:^\/^\/example.com^\^",^\^"action^\^":^\^"pdf^\^",^\^"options^\^":^{^\^"args^\^":^[^],^\^"viewport^\^":^{^\^"width^\^":800,^\^"height^\^":600^}^}^}^"" failed.

ERROR: The process "8928" not found.
{ Error: Protocol error (IO.read): Target closed.
    at Promise (~\node_modules\puppeteer\lib\Connection.js:183:56) 
    at new Promise (<anonymous>)
    at CDPSession.send (~\node_modules\puppeteer\lib\Connection.js:182:12) 
    at Function.readProtocolStream (~\node_modules\puppeteer\lib\helper.js:250:37) 
    at Page.pdf (~node_modules\puppeteer\lib\Page.js:994:25) 
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Page.<anonymous> (~\node_modules\puppeteer\lib\helper.js:111:15) 
    at getOutput (~\vendor\spatie\browsershot\bin\browser.js:26:40) 
    at callChrome (~\vendor\spatie\browsershot\bin\browser.js:171:24) 
    at process._tickCallback (internal/process/next_tick.js:68:7) message: 'Protocol error (IO.read): Target closed.' }`

**Comment by maltonite** [comment]
After further investigation, it appears to be an issue with Apache, switching over to using Nginx solved the issue. I assume it is a permission issue.

**Comment by AlbertMulaki** [comment]
Thanks. Will check and let you know.

**Comment by gofish543** [comment]
> After further investigation, it appears to be an issue with Apache, switching over to using Nginx solved the issue. I assume it is a permission issue.

I've been hounded by this issue on a fresh Windows 10 development environment for weeks now. This is the solution!!!

 You, my friend, are a god. Thank you so much

**Comment by mansoorkhan96** [comment]
> After further investigation, it appears to be an issue with Apache, switching over to using Nginx solved the issue. I assume it is a permission issue.

You are such a life saver man. 
Hugs, Hugs and so many hugs to you.
