### ISSUE TITLE
When saving a pdf as (A4) I have a lot of whitespace at top

### ISSUE THREAD

**Issue by aFluxx** [spatie/browsershot#360]
Hello there,

When I save a pdf I'm losing a lot of whitespace at top of the pdf, as marked in yellow on this screenshot:
![](https://i.gyazo.com/6fa8239f8dd95447b196ac4f0115d4a9.png)

Is there I way I can force the printing to start at the top of the page?

**Comment by Kocal** [comment]
I think it's because of margings.

**Comment by aFluxx** [comment]
Indeed, I was thinking in the same direction.

Was wondering if there's a way to set margins.
I tried https://github.com/spatie/browsershot#setting-margins

But that doesn't seem to work with custom margins.
