### ISSUE TITLE
Selecting elements for click

### ISSUE THREAD

**Issue by jrean** [spatie/browsershot#361]
Hi,

While using the `click()` method. How do you write a selector to select the element number n?

For instance, I have a list and I would like to click one by one on each item. I use a `for` loop (after calculating how many items the list have)
`->click("#xx > div:nth-child($i) .yyy")`

It works but always returns the first element of the list.

Can I get some help?

Thx.

**Comment by intrepidws** [comment]
@jrean Did you end up solving this problem?

**Comment by jrean** [comment]
@intrepidws No :/
