### ISSUE TITLE
Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command "node...

### ISSUE THREAD

**Issue by Marion64** [spatie/browsershot#369]
I have globally installed puppeteer and windows installed composer, everything looks fine I think I should be able to execute the code:

use Spatie\Browsershot\Browsershot;
require __DIR__ . '/vendor/autoload.php';

$pathToImage = getcwd()."something.jpeg";
Browsershot::url('https://www.w3schools.com/')->save($pathToImage);

without a problem however when I go to the file in my localhost (XAMPP) All I get is

Fatal error: Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command "node ^"D:^\xampp^\htdocs^\composertest^\vendor^\spatie^\browsershot^\src/../bin/browser.js^" ^"^{^\^"url^\^":^\^"https:^\/^\/www.w3schools.com^\/^\^",^\^"action^\^":^\^"screenshot^\^",^\^"options^\^":^{^\^"type^\^":^\^"jpeg^\^",^\^"path^\^":^\^"D:^\^\xampp^\^\htdocs^\^\composertestsomething.jpeg^\^",^\^"quality^\^":100,^\^"args^\^":^[^],^\^"viewport^\^":^{^\^"width^\^":800,^\^"height^\^":600^},^\^"disableJavascript^\^":true^}^}^"" failed. Exit Code: 1(General error) Working directory: D:\xampp\htdocs\composertest Output: ================ Error Output: ================ internal/modules/cjs/loader.js:638 throw err; ^ Error: Cannot find module 'puppeteer' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15) at Function.Module._load (internal/modules/cjs/loader.js:562:25) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js: in D:\xampp\htdocs\composertest\vendor\spatie\browsershot\src\Browsershot.php on line 705

What's going on?

**Comment by aelliott1485** [comment]
I see the same issue if I install puppeteer globally, but if I add it locally then that message goes away. I tried setting the [custom node module path](https://github.com/spatie/browsershot#user-content-custom-node-module-path) but that didn't help in initial attempts. If I get it working then I will edit this post with my findings.

**Comment by Marion64** [comment]
@aelliott1485 Yes, thank you that fixed it! You are amazing have a great day.

**Comment by nguyentrongchinh1997** [comment]
I can't fix it. How to fix?. Thanks

**Comment by Kamleshpaul** [comment]
i m also getting same issue with Linux :-1:

**Comment by SudoGetBeer** [comment]
> Error: Cannot find module 'puppeteer'

Usually you are missing the puppeteer js requirement described here: https://github.com/spatie/browsershot#requirements
That fixed it for me every time. If you install pupeteer globally it could be that you need to set the right node or npm path with one of these:
`
            ->setNodeBinary($nodePath)
            ->setNpmBinary($npmPath)
`

**Comment by PayteR** [comment]
@SudoGetBeer 

I'm using Windows 10, and I met the requirements. I installed puppeteer globally and it didn't help. Then I found this thread and tried:
```
Browsershot::url($url)
    ->setNodeBinary('C:\Progra~1\nodejs\node.exe') 
    ->setNpmBinary('C:\Users\payte\AppData\Roaming\npm\npm')
    ->setNodeModulePath('C:\Users\payte\AppData\Roaming\npm\node_modules')
    ->save(__DIR__ . '/output.jpg');
```
And it still says `Error: Cannot find module 'puppeteer'`

BTW note `C:\Progra~1\nodejs\node.exe` path, this is because it will not work when there are spaces in path https://stackoverflow.com/questions/17845809/c-program-is-not-recognized-error
