### ISSUE TITLE
Taking screenshot after a set period of time, even if assets aren't fully loaded

### ISSUE THREAD

**Issue by chrisgherbert** [spatie/browsershot#370]
It would be great to have an option to take a screenshot after a set period of time, even if the page assets haven't completely loaded.  Many of the pages that I'm capturing are visually complete within few seconds, but don't fully load their assets for over a minute.  I'd don't want to wait forever for them to load completely, and I'd also rather not simply have them time out and fail to take a screenshot at all.

**Comment by freekmurze** [comment]
Feel free to PR new functionality.
