### ISSUE TITLE
Set height on pdf

### ISSUE THREAD

**Issue by mihaliak** [spatie/browsershot#38]
Hey, PhantomJS is supporting to render pdf instead of images but it throws exception because `ImageManager` which is used to resize image is using `getimagesize` which doesn't work with pdf.

Is there any way how to resize pdf?

`$browsershot = new \Spatie\Browsershot\Browsershot();
    $browsershot
        ->setURL('http://www.arstechnica.com')
        ->setWidth(595)
        ->setHeight(842)
        ->setTimeout(5000)
        ->save('result.pdf');`

Using `setHeight(842)` throws `NotReadableException` when I change it to 0 or use `setHeightToRenderWholePage` it works but I need to crop it.

Thanks.

**Comment by freekmurze** [comment]
As PhantomJS has been abandoned we're probably not going to put more work in this version of the package. 

My suggestion would be to perform any manipulations with [spatie/image](https://docs.spatie.be/image)
