### ISSUE TITLE
Is there a way to wait for network to idle for X seconds?

### ISSUE THREAD

**Issue by N1njaWTF** [spatie/browsershot#393]
Hello
> Using the waitUntilNetworkIdle() method you can tell Browsershot to wait for a period of 500 ms with no network activity before taking the screenshot, ensuring all additional resources are loaded.

Can I adjust the waiting period to more than 500ms of no network activity?

Thanks!

**Comment by guimcaballero** [comment]
This seems to be a Puppeteer hardcoded setting, you can read more about it here https://github.com/puppeteer/puppeteer/issues/1353.

There seem to be some workarounds in that thread that could be implemented.

**Comment by N1njaWTF** [comment]
> This seems to be a Puppeteer hardcoded setting, you can read more about it here [puppeteer/puppeteer#1353](https://github.com/puppeteer/puppeteer/issues/1353).
> 
> There seem to be some workarounds in that thread that could be implemented.

Thanks..

I've also found this: https://github.com/puppeteer/puppeteer/issues/3305
I am not entirely sure tho if that is supported in browsershot?
