### ISSUE TITLE
Support for puppeteer-core

### ISSUE THREAD

**Issue by vdwijngaert** [spatie/browsershot#394]
Would it be useful to support both puppeteer and [puppeteer-core](https://www.npmjs.com/package/puppeteer-core)? When short on space, you probably don't want the puppeteer package downloading chromium. I'm currently running it in an alpine-based container with a custom chromium installed, so I'd rather use puppeteer-core. 

Not entirely sure, but this probably also applies when using a remote instance.

> **puppeteer-core**
> Since version 1.7.0 we publish the puppeteer-core package, a version of Puppeteer that doesn't download any browser by default.

I'm not looking to maintain my own `browser.js`, so I'm using [cweagans/composer-patches](https://github.com/cweagans/composer-patches) to patch the first line of `browser.js`.

```diff
diff --git a/bin/browser.js b/bin/browser.js
index 14cf84d..ba401e1 100755
--- a/bin/browser.js
+++ b/bin/browser.js
@@ -1,4 +1,4 @@
-const puppeteer = require('puppeteer');
+const puppeteer = require('puppeteer-core');
 const fs = require('fs');
 const URL = require('url').URL;
 const URLParse = require('url').parse;
```

**Comment by freekmurze** [comment]
I don't have a need for this myself, so probably won't invest time in it. Feel free to PR non breaking changes to support if you need it.

**Comment by CImrie** [comment]
For anyone coming to this in the future, you can easily achieve this without browsershot supporting puppeteer-core officially.
Using npm aliases you can fake puppeteer-core as puppeteer.

`npm install puppeteer@npm:puppeteer-core --save`

**Comment by mtpiercey** [comment]
> For anyone coming to this in the future, you can easily achieve this without browsershot supporting puppeteer-core officially.
> Using npm aliases you can fake puppeteer-core as puppeteer.
> 
> `npm install puppeteer@npm:puppeteer-core --save`

Can confirm this trick works, thanks!
Doesn't seem to work for Windows, but I got it working on macOS, at least.

Here's what else I did to get `puppeteer-core` to cooperate without hard-coding the Chrome path:

In the `.env` of my Laravel app:
```
# Note the single quotes around the path
CHROME_PATH='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
```

And here's a snippet from my opengraph image generator:
```
$screenshot = Browsershot::html($image_html)
          ->setChromePath(env('CHROME_PATH'))
          ->windowSize(1200, 627)
          ->screenshot();
```

**Comment by tobz-nz** [comment]
I tried the alias trick, but it doesn't seem to work in my Docker based environment.

I get this error:

```bash
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (991974).
    at ChromeLauncher.launch (/container/application/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:105:23)
    at async callChrome (/container/application/vendor/spatie/browsershot/bin/browser.js:68:23)
```

Even though I'm telling it to use a remoteInstance.

```php
\Spatie\Browsershot\Browsershot::url('https://example.com')
    ->setRemoteInstance('remote-puppet', 9222)
    ->noSandbox()
    ->bodyHtml()
```

It works if I call it from my local docker instance (laravel sail), but not from production (a custom image I don't have access to - managed by my host)

Anyone had anything similar or could point me in the right direction to look for a fix?
