### ISSUE TITLE
When a video player on the page last version does not work

### ISSUE THREAD

**Issue by IvanovPavel** [spatie/browsershot#404]
When I use a version 3.34.0 - I could make a screenshots with video player on the page. After update to 3.36.0 this functionality disappeared.
Try to make screenshot from twitch.tv any channel for example.

PS: use google-chrome-stable as a main browser (setChromePath point to)

**Comment by freekmurze** [comment]
Probably this is caused by the underlying Chrome browser or puppeteer. Try to reproduce that error directly with one of those two and report the error on their repo.
