### ISSUE TITLE
Add support for puppeteer v5.0.0 - page.emulateMediaType

### ISSUE THREAD

**Issue by litan1106** [spatie/browsershot#407]
[puppeteer v5.0.0](https://github.com/puppeteer/puppeteer/releases/tag/v5.0.0)

**Removal of page.emulateMedia**
This method was deprecated and is now removed from Puppeteer. Swap to page.emulateMediaType which behaves identically.

**Comment by darkons** [comment]
Meanwhile, you can use `setOption('emulateMediaType', 'screen')`

**Comment by freekmurze** [comment]
I'd accept a PR that adds support for `page.emulateMediaType`.

**Comment by litan1106** [comment]
@darkons thanks for the quick solution. ->setOption('emulateMediaType', 'screen')
