### ISSUE TITLE
How to set generated today date format ?

### ISSUE THREAD

**Issue by sergeynilov** [spatie/browsershot#410]
Hello,
Generating pdf with spatie/browsershot I use date class for showing
current date as written here :
https://github.com/spatie/browsershot#headers-and-footers

with code like :

```
       $footerHtml.= '       ...
                            Printed on: <span class=\'date\'></span>
                             ...  
';

        $footerHtml.= '            </tbody></table>             
        </div>';

        Browsershot::html(htmlspecialchars_decode($pdf_content))
            ->showBrowserHeaderAndFooter()
            ->footerHtml($footerHtml)
            ->showBackground()
            ->margins(20, 10, 20, 10)
            ->setOption('addStyleTag', json_encode(['content' => '.block_wrapper {
            background-color : red; !important;
            border: 0px dotted red !important;
        }

```
But the thing is that genarated date is in different format “7/14/2020”, but I use date format like 
“14 July, 2020”, which I generate with Carbon formatLocalized method
1) How can I change today format ?
2) Also I see that at the top left corner of generated pdf file I see “7/14/2020” value of current date
but I did not set it in my code ... It looks like automatic value. Can I get id of it?

```
        "laravel/framework": "5.7.*",
        "spatie/browsershot": "^3.37",

```
Thanks!

**Comment by riasvdv** [comment]
This is a feature of the underlying chrome browser that puppeteer uses, there seems to be no way to change the format, I suggest using PHP to just show the current date when generating the PDF
