### ISSUE TITLE
Generate pdf from html issue when PrivateTmp is true

### ISSUE THREAD

**Issue by faculezcano** [spatie/browsershot#415]
Hi! first thanks for so useful package, im experiencing troubles on Amazon EBS environment where the php systemd process have PrivateTmp active, so when php asks for /tmp actually is writing to a private tmp generated by systemd. Im using html() function to generate a pdf, since it saves a index.html to /tmp, when puppeeter tries to access the file in /tmp/xxxxxx/index.html file isnt there.

Greetings

**Comment by ugurarici** [comment]
Can you please explain how did you solve this?

**Comment by faculezcano** [comment]
There wasn't any problem with BrowserShot, was my fault.

**Comment by rwdevguy** [comment]
@faculezcano  What did you do differently to solve the issue?
