### ISSUE TITLE
Bigger headers/footers throw "Command exceeds the allowed length of 8192 bytes" on Windows 

### ISSUE THREAD

**Issue by spackmat** [spatie/browsershot#419]
We have a header with an inlined image to appear on every page. On my colleague's macOS dev machine that isn't a problem, but on my Windows dev machine, I get a "Command exceeds the allowed length of 8192 bytes" error thrown, when I try to render that PDF.

I can reproduce that problem also with other header and footer content exceeding that 8192 bytes together. Form my understanding this is because the header and the footer template are passed to chromium via the command line and Windows has that annoying 8192 bytes limit for that.

My question is now: **Can this be fixed at all?** Is there another way to pass the header and footer templates? Maybe instead of throwing a very long parameter string at the called binary, a file containing the command parameters could be used ([as described here](https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation))?

P.S.: The image within the header is inlined in our case, because there is no public endpoint for it to be referenced and loaded via network by design (it is a logo coming from the database inside a secured backend). I consider this a quite common usecase when rendering PDFs from internal systems. I could write such an endpoint and throw around some authentication stuff to read from that to avoid inlining that image, but maybe there is a better solution for that.

**Comment by freekmurze** [comment]
We don't use Windows ourselves, so we're not going to invest time in this. Feel free to investigate further on your own. Should this error be fixable by the package, I'd accept a PR.

**Comment by spackmat** [comment]
Okay. I had a very quick look into the browsershot code and didn't find any command line parameter stuff. Am I right that this more of a puppeteer problem and had to be fixed over there?

I think it would be fixable by throwing the parameters to chromium not directly via cli on windows and instead write a parameter temp file and feed that into chromium. Sounds like puppeteer stuff.
