### ISSUE TITLE
Exit Code: 1(General error)

### ISSUE THREAD

**Issue by steph1902** [spatie/browsershot#420]
Hi, I have followed all the steps and I'm really stuck because the error is too general, here is the error code that I got

`The command "node ^"C:^\laragon^\www^\abc^\vendor^\spatie^\browsershot^\src/../bin/browser.js^" ^"^{^\^"url^\^":^\^"file:^\/^\/C:^\^\Users^\^\User^\^\AppData^\^\Local^\^\Temp^\^\148969017-0016706001600598341^\^\index.html^\^",^\^"action^\^":^\^"pdf^\^",^\^"options^\^":^{^\^"path^\^":^\^"example.pdf^\^",^\^"args^\^":^[^],^\^"viewport^\^":^{^\^"width^\^":800,^\^"height^\^":600^},^\^"displayHeaderFooter^\^":false^}^}^"" failed. Exit Code: 1(General error) Working directory: C:\laragon\www\abc\public Output: ================ Error Output: ================ (node:44284) ExperimentalWarning: The fs.promises API is experimental { Error: Protocol error (IO.read): Target closed. at Promise (C:\laragon\www\abc\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:208:63) at new Promise () at CDPSession.send (C:\laragon\www\abc\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:207:16) at Object.readProtocolStream (C:\laragon\www\abc\node_modules\puppeteer\lib\cjs\puppeteer\common\helper.js:176:39) message: 'Protocol error (IO.read): Target closed.' }`

my code from controller is
`return Browsershot::html('<h1>Hello world!!</h1>')->save('example.pdf');`

please give me any clue, thank you

**Comment by freekmurze** [comment]
Unfortunately I can't see the cause of the error. It's probably something to do with your specific environment. Should you find the package is in error, I'd accept a PR to fix it.
