### ISSUE TITLE
Symfony\Component\Process\Exception\ProcessFailedException

### ISSUE THREAD

**Issue by TargiX** [spatie/browsershot#421]
Hi there, I'm trying to setup browsershot, I'm on windows and getting some general ProcessFailedException. 

Here is the full error, 
[https://flareapp.io/share/KPg1Oe5a#F43](https://flareapp.io/share/KPg1Oe5a#F43)

It will be great if can you point me where is the issue. Thanks!

**Comment by freekmurze** [comment]
Unfortunately I can't see the cause of the error. It's probably something to do with your specific environment. Should you find the package is in error, I'd accept a PR to fix it.

**Comment by TargiX** [comment]
> Unfortunately I can't see the cause of the error. It's probably something to do with your specific environment. Should you find the package is in error, I'd accept a PR to fix it.

@freekmurze 
But how I can debug what's wrong if your package doesn't throw any errors? You closed similar issue - https://github.com/spatie/browsershot/issues/403  and sad that there was too little info, and I sent you a full stack trace which is pointing to browserstack that throws error without any details. How do you suggest to debug it?

**Comment by cjaoude** [comment]
Beware, some Blade template tags cause this issue. eg. `{{ asset('path/foo') }} caused this timeout.

Don't know exactly why, but reproducible on a clean-sheet Laravel app I tested.
