### ISSUE TITLE
Problem in load in cpanel

### ISSUE THREAD

**Issue by sardarn** [spatie/browsershot#422]
Hi

my project works in local normally. when i upload project in cpanel and run it, i get this eroor. what is the problem?
node is running in my host.

The command "PATH=$PATH:/usr/local/bin NODE_PATH=npm root -g node '/home2/connectt/public_html/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"https://rahavard365.com/marketmap","action":"screenshot","options":{"type":"jpeg","path":"/home2/connectt/public_html/public/screens/12313.jpeg","args":[],"viewport":{"width":1024,"height":768},"fullPage":true}}'" failed. Exit Code: 127(Command not found) Working directory: /home2/connectt/public_html/public Output: ================ Error Output: ================ sh: npm: command not found sh: node: command not found

**Comment by spaceemotion** [comment]
Since you're mentioning cPanel I guess you're using a shared webspace? Browsershot requires `npm` to be installed, which does not seem to be the case for you.
