### ISSUE TITLE
The process "node ^"C:^\xampp^\htdocs^\projectname^\vendor^\spatie^\browsershot^\src/../bin/browser.js^" ^"^{^\^"url^\^":^\^"https:^\/^\/google.com^\^",^\^"action^\^":^\^"screenshot^\^",^\^"options^\^":^{^\^"type^\^":^\^"png^\^",^\^"path^\^":^\^"screenshots^\/10^\/5f75ea0368e7c.jpeg^\^",^\^"args^\^":^[^\^"--no-sandbox^\^"^],^\^"viewport^\^":^{^\^"width^\^":1920,^\^"height^\^":1080^},^\^"waitUntil^\^":^\^"networkidle0^\^",^\^"ignoreHttpsErrors^\^":true,^\^"timeout^\^":120000^}^}^"" exceeded the timeout of 120 seconds.

### ISSUE THREAD

**Issue by skittery** [spatie/browsershot#424]
Hi,
I got the browsershot package to work properly - however:
On some URLs it takes WAY too long to work, and at the end I get an error. Like the following:

`The process "node ^"C:^\xampp^\htdocs^\projectname^\vendor^\spatie^\browsershot^\src/../bin/browser.js^" ^"^{^\^"url^\^":^\^"https:^\/^\/google.com^\^",^\^"action^\^":^\^"screenshot^\^",^\^"options^\^":^{^\^"type^\^":^\^"png^\^",^\^"path^\^":^\^"screenshots^\/10^\/5f75ea0368e7c.jpeg^\^",^\^"args^\^":^[^\^"--no-sandbox^\^"^],^\^"viewport^\^":^{^\^"width^\^":1920,^\^"height^\^":1080^},^\^"waitUntil^\^":^\^"networkidle0^\^",^\^"ignoreHttpsErrors^\^":true,^\^"timeout^\^":120000^}^}^"" exceeded the timeout of 120 seconds.`

This specifically was for google.com but this happens on several other sites as well.

The relevant part of my code:

`        Browsershot::url($url)
            ->windowSize(1920, 1080)
            ->fit(Manipulations::FIT_CONTAIN, 500, 500)
            ->noSandbox()
            ->waitUntilNetworkIdle()
            ->ignoreHttpsErrors()
            ->timeout(120)
            ->save($id);

I'm using this on a Laravel 8 project, running on Xampp with PHP 7.2.18

Also, there was one site I tried and I ended up getting to a capcha screen. Is there any way around this?

Thanks in advance.`

**Comment by freekmurze** [comment]
I haven't come across this problem myself and I don't this this problem needs to be addressed in the package. It will propably be cause by something in puppeteer or Chrome.

 Should you find that the package is caused this issue, feel free to PR the fix.

**Comment by BestPluginsWordpress** [comment]
@skittery Did you solve this? I'm having the same error.

**Comment by skittery** [comment]
No.
Never got it to work.

**Comment by BestPluginsWordpress** [comment]
Thank you for the quick reply!

ma 26. lokak. 2020 klo 18.59 skittery (notifications@github.com) kirjoitti:

**Comment by millman2394** [comment]
same error (60 seconds)
