### ISSUE TITLE
I have a little problem when I use your script in a mysql loop

### ISSUE THREAD

**Issue by Benjouke** [spatie/browsershot#430]
Hello,

I have a little problem when I use your script in a mysql loop, indeed, when there is a timeout on a url the script stops and does not continue for other sites, do you know how can I make the script continue after a timeout on a URL?

`while($row = $result->fetch_array(MYSQLI_ASSOC))
{	
	Browsershot::url($row['url'])
    ->timeout(60)
	->save('/screenshots/'.$row['sites'].'.png');
	
}`

thank you in advance

**Comment by freekmurze** [comment]
The right fix is environment dependant. The easiest thing you could to is increase the amount of time that PHP is allowed to run.
