### ISSUE TITLE
Getting erro while trying to create pdf using browsershot

### ISSUE THREAD

**Issue by onlinecheckwriter** [spatie/browsershot#437]
Browsershot::url("$url")->waitUntilNetworkIdle()->noSandbox()->ignoreHttpsErrors()->savePdf($save_to_file);

The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/home/forge/sandbox.onlinecheckwriter.com/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"url","action":"pdf","options":{"path":"\/home\/forge\/url\/storage\/pdf_v_dd15e527-ffc5-4019-ae04-4818365b7cf9.pdf","args":["--no-sandbox"],"viewport":{"width":800,"height":600},"waitUntil":"networkidle0","ignoreHttpsErrors":true}}'" failed. Exit Code: 1(General error) Working directory: /home/forge/sandbox.onlinecheckwriter.com/public Output: ================ Error Output: ================ Error: Protocol error (Page.printToPDF): Show invalid printer settings error at /usr/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63 at new Promise (<anonymous>) at CDPSession.send (/usr/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16) at Page.pdf (/usr/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1212:43) at getOutput (/home/forge/sandbox.onlinecheckwriter.com/vendor/spatie/browsershot/bin/browser.js:27:40) at callChrome (/home/forge/sandbox.onlinecheckwriter.com/vendor/spatie/browsershot/bin/browser.js:223:24) at processTicksAndRejections (internal/process/task_queues.js:97:5)

Any suggestion?

**Comment by MJunaidAhmad** [comment]
You need to find the path of node and npm by using this command: `which node` & `which npm`
After that you can use these function to set binaries manually: `Browsershot::url("$url")->waitUntilNetworkIdle()->noSandbox()->ignoreHttpsErrors()->setNodeBinary('/usr/bin/node')->setNpmBinary('/usr/bin/npm')->savePdf($save_to_file);`
