### ISSUE TITLE
PDF style is broken in 3.40.1

### ISSUE THREAD

**Issue by martijnderidder** [spatie/browsershot#443]
We are using Browsershot to make invoices in our system. Since the update to `3.40.1` the style is broken, the header and footer are working, but the main content is styleless. If i lock the version to `3.40.0` everything still works.

We use this code to generate a PDF file;
```
            $browsershot = Browsershot::html($sections['body'])
            ->format('A4')
            ->margins(28, 6, 14, 6, 'mm')
            ->showBrowserHeaderAndFooter()
            ->headerHtml($sections['header'])
            ->footerHtml($sections['footer'])
            ->showBackground()
            ->addChromiumArguments([
                'font-render-hinting' => 'none',
            ])
            ->waitUntilNetworkIdle();
```

![image](https://user-images.githubusercontent.com/8685319/98555848-b3b59400-22a2-11eb-8d6d-f12881ed0adc.png)

**Update**
For reference, the PDF looks like this when using version `3.40.0`:
![image](https://user-images.githubusercontent.com/8685319/98556321-376f8080-22a3-11eb-9387-c052d7a69562.png)

**Comment by freekmurze** [comment]
@dr4gonw4ll  could you take a look at this. Your recent change is the only difference between 3.40.0 and 3.40.1

**Comment by dr4gonw4ll** [comment]
Hello @martijnderidder - The new update uses page.setContent puppeteer function to render the HTML to mitigate security issue.
Hello @freekmurze - I just saw that the page.setContent Puppeteer API have some bugs with loading up of CSS content https://github.com/puppeteer/puppeteer/issues/6590 and https://github.com/puppeteer/puppeteer/issues/5191. If the functionality is breaking then its better to role back and find an alternate fix. Sorry for the inconvenience.

**Comment by freekmurze** [comment]
I've reverted the changes. The latest version should work properly again.
