### ISSUE TITLE
The command PATH=$PATH:/usr/local/bin NODE_PATH=`/usr/bin/nodejs .....  failed.

### ISSUE THREAD

**Issue by bogdanovmaxim87** [spatie/browsershot#446]
Not sure what I am doing wrong. But getting such error: https://take.ms/FHox4 - sounds like paths incorrect - but I've checked those paths 100 times. They totally fine. Any help appreciate.

Tried that https://github.com/spatie/browsershot/issues/437 varian - but didn't helped. 

Thanks.

**Comment by bogdanovmaxim87** [comment]
Sorry, Can be closed. Figure out.

**Comment by jackkemmish** [comment]
Hi there, what did you do to resolve as I think I have to same issue?

**Comment by bogdanovmaxim87** [comment]
Hi there.... If I remember correctly, you need to install correct chrome headless browser on your machine. I was using ubuntu 16.04, so my installation was:
apt-get install libnss3-dev
apt-get install libatk-bridge2.0-0
apt-get install libx11-xcb1
apt-get install libdrm2
apt-get install libxkbcommon-x11-0
apt-get install libxcomposite1
apt-get install libxdamage1
apt-get install libxfixes3
apt-get install libxrandr2
apt-get install libwayland-client0
apt-get install libgtk-3-0
apt-get install libasound2

And this is my code for making a screenshot:
$Browsershot::url($this->url)
            ->waitUntilNetworkIdle()
            ->noSandbox()
            ->ignoreHttpsErrors()
            ->setNodeBinary('/usr/bin/node')
            ->setNpmBinary('/usr/bin/npm')
            ->windowSize(300, 300)
            ->save($this->filePath());

Hope that help.

**Comment by jackkemmish** [comment]
Thanks for the reply!

Cool so I assume it works a little differently to my local version then as all I did locally was run `npm install puppeteer` within my project and things were working.

But I'll take a look at that thanks. 

How do you determine the `->setNodeBinary('/usr/bin/node')` and `->setNpmBinary('/usr/bin/npm')`? When I run `which node` on my server I get `/home/master/.nvm/versions/node/v10.18.1/bin/node` for example. But routing that doesn't make a difference :/ 

I don't know if this makes a difference but it's a wordpress project, and I ran all the commands in the project folder. Hmmmm

Sorry for the long message!

**Comment by bogdanovmaxim87** [comment]
Hmmmm..... Try to figure out if you have a correct permissions on node and npm.

**Comment by jackkemmish** [comment]
Yeah I have a feeling that could be the issue. I’m using cloudways and have no root access. I’m going to give either Forge or Runcloud a go!

Thanks for replying!

**Comment by bogdanovmaxim87** [comment]
Heh. Good luck with that :)

P.S. That's why I prefer to have clear server, where you are controlling everything :).

**Comment by jackkemmish** [comment]
Yeah I’ve learn’t that now haha! Thanks again

**Comment by charul1234** [comment]
> Hi there.... If I remember correctly, you need to install correct chrome headless browser on your machine. I was using ubuntu 16.04, so my installation was:
> apt-get install libnss3-dev
> apt-get install libatk-bridge2.0-0
> apt-get install libx11-xcb1
> apt-get install libdrm2
> apt-get install libxkbcommon-x11-0
> apt-get install libxcomposite1
> apt-get install libxdamage1
> apt-get install libxfixes3
> apt-get install libxrandr2
> apt-get install libwayland-client0
> apt-get install libgtk-3-0
> apt-get install libasound2
> 
> And this is my code for making a screenshot:
> $Browsershot::url($this->url)
> ->waitUntilNetworkIdle()
> ->noSandbox()
> ->ignoreHttpsErrors()
> ->setNodeBinary('/usr/bin/node')
> ->setNpmBinary('/usr/bin/npm')
> ->windowSize(300, 300)
> ->save($this->filePath());
> 
> Hope that help.

Thank you, 
After installing the above dependencies. 
it's working

**Comment by bogdanovmaxim87** [comment]
@charul1234 - cool ha?!

**Comment by jackkemmish** [comment]
Worked like a charm. I had to change hosting provider, but the code above was exactly what I was after! Thanks again for your help 👍

**Comment by bogdanovmaxim87** [comment]
sure! Glad it helped

**Comment by cjaoude** [comment]
Beware, some Blade template tags cause this issue. eg. `{{ asset('path/foo') }} caused this timeout.
