### ISSUE TITLE
Trying to use with Laravel 5.2.* and PhP 7.1

### ISSUE THREAD

**Issue by remoteeng00** [spatie/browsershot#451]
Hi,

I am trying to use this package with my project and it throws following erros.

Problem 1
    - Installation request for spatie/browsershot ^3.41 -> satisfiable by spatie/browsershot[3.41.0].
    - Conclusion: remove symfony/process v3.0.9
    - Conclusion: don't install symfony/process v3.0.9
    - spatie/browsershot 3.41.0 requires symfony/process ^5.0 -> satisfiable by symfony/process[v5.0.0, v5.0.1, v5.0.10, v5.0.11, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9, v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0].
    - Can only install one of: symfony/process[v5.0.0, v3.0.9].
    - Can only install one of: symfony/process[v5.0.1, v3.0.9].
    - Can only install one of: symfony/process[v5.0.10, v3.0.9].
    - Can only install one of: symfony/process[v5.0.11, v3.0.9].
    - Can only install one of: symfony/process[v5.0.2, v3.0.9].
    - Can only install one of: symfony/process[v5.0.3, v3.0.9].
    - Can only install one of: symfony/process[v5.0.4, v3.0.9].
    - Can only install one of: symfony/process[v5.0.5, v3.0.9].
    - Can only install one of: symfony/process[v5.0.6, v3.0.9].
    - Can only install one of: symfony/process[v5.0.7, v3.0.9].
    - Can only install one of: symfony/process[v5.0.8, v3.0.9].
    - Can only install one of: symfony/process[v5.0.9, v3.0.9].
    - Can only install one of: symfony/process[v5.1.0, v3.0.9].
    - Can only install one of: symfony/process[v5.1.1, v3.0.9].
    - Can only install one of: symfony/process[v5.1.2, v3.0.9].
    - Can only install one of: symfony/process[v5.1.3, v3.0.9].
    - Can only install one of: symfony/process[v5.1.4, v3.0.9].
    - Can only install one of: symfony/process[v5.1.5, v3.0.9].
    - Can only install one of: symfony/process[v5.1.6, v3.0.9].
    - Can only install one of: symfony/process[v5.1.7, v3.0.9].
    - Can only install one of: symfony/process[v5.1.8, v3.0.9].
    - Can only install one of: symfony/process[v5.1.9, v3.0.9].
    - Can only install one of: symfony/process[v5.2.0, v3.0.9].
    - Installation request for symfony/process (locked at v3.0.9) -> satisfiable by symfony/process[v3.0.9].

Installation failed, reverting ./composer.json to its original content.

**Comment by nconroy** [comment]
Use the last version that is compatible with those:
composer require "spatie/browsershot:2.4.*"
