### ISSUE TITLE
symfony/process Package Compatability Issue version 3 vs 4

### ISSUE THREAD

**Issue by nithinp89** [spatie/browsershot#455]
Hi Guys,

Thank you for your excellent work as always. 

We trying to figure out to use Browserhot v2 with Laravel 6 however package was not installing due to symfony/process Package Compatability Issue.

Laravel 6 require below version:

"symfony/process": "^4.3.4",

However, Browserhot v2 requires the below version: 

"symfony/process": "^3.0"

Is it possible to adjust the requirement on your side to have "symfony/process": "^4.0", if there is no breaking changes?

Thanks in advance.

**Comment by freekmurze** [comment]
Feel free to send in a PR for this
