### ISSUE TITLE
NotReadableException on PDF generation

### ISSUE THREAD

**Issue by elamotte** [spatie/browsershot#46]
Hi,

Unable to read image from file`

When I generate a PDF the file is correctly created but I have this error raised in the browser.

**The error:**
`NotReadableException in Decoder.php line 20:`

**Here is the code :** 
```
$pdf = new \Spatie\Browsershot\Browsershot();
$pdf->setURL('http://app.dev/test/rsujnnongalpw6n')
        ->setWidth(850)
        ->setHeight(1100)
        ->save(storage_path('app/test.pdf'));
```

**Comment by elamotte** [comment]
A bit more infos, it's looks like it's due to the PDF format.

I try to change the last line for : 
`->save(storage_path('app/test.png'));`

And the error was not raised.

**Comment by freekmurze** [comment]
Seems like the underlying binary cannot create PDF's. 

These types are supported: png, jpg, jpeg, ppm, bmp, pdf, gif.

**Comment by elamotte** [comment]
Ok but in the list you just sent "pdf" is mentionned... 

> These types are supported: png, jpg, jpeg, ppm, bmp, **pdf,** gif.

**Comment by freekmurze** [comment]
Dammit, my eye didn't catch that. 🤣 Sorry for the confusion. I copied that list from the phantomjs docs. Our package does nothing for the pdf rendering itself. 

Sadly work on phantomjs has been discontinued, so if you're experiencing troubles with it, it's best to manually convert the image to a good pdf or move on to another solution.

**Comment by elamotte** [comment]
Ok perfect thanks a lot for your feedback, and your work on this :).
I'll look for a good way to convert to PDF.
