### ISSUE TITLE
ERROR 500 on AWS EC2 AMI (Fedora/CENTOS)

### ISSUE THREAD

**Issue by inglesuniversal** [spatie/browsershot#47]
Hi after installing through COMPOSER I got an ERROR 500 on my apache server... Can you please help

`<?php
// BROWSERSHOT

require '/var/www/html/vendor/autoload.php';

    $browsershot = new \Spatie\Browsershot\Browsershot();
    $browsershot
        ->setURL('http://www.arstechnica.com')
        ->setBinPath('/var/www/html/vendor/spatie/browsershot/bin/phantomjs')
        ->setWidth(1024)
        ->setHeight(768)
        ->setTimeout(5000)
        ->save('/var/www/html/api/browsershot/img/arstechnica-browsershot.jpg');
        
        `

**Comment by freekmurze** [comment]
Probably the binary included in this package is not ment to be run on Centos.

**Comment by inglesuniversal** [comment]
GREAT NEWS... Now you can add to your notes, that your script WORKED on CENTOS / FEDORA ... What I found was that the path to the binary package was missing... In my case I used:


`        ->setBinPath('/var/www/html/vendor/spatie/browsershot/bin/phantomjs')    `

BEAUTIFUL CODE you made (Yoda style)!!!

NOW as per suggestions... Do you thing you can add coordinates to grab ONLY a portion of the fetched URL.... Congrats!!!!
