### ISSUE TITLE
page.waitForTimeout is not a function

### ISSUE THREAD

**Issue by niconico291** [spatie/browsershot#475]
I think its related to #452 

Whenever I add `setDelay` I now get:

TypeError: page.waitForTimeout is not a function at callChrome (/Users/user/project/vendor/spatie/browsershot/bin/browser.js:221:24) 

I ran composer update.

**Comment by niconico291** [comment]
Ups, my bad. I had an old puppeteer version.

**Comment by stayallive** [comment]
I get the same error and have tried Puppeteer 4 through 7 but no version seems to be working.

From what I can tell you need Puppeteer > 5.4.0 but installing 5.5.0 or 6 or 7 doesn't look to be working.

What version are you running now?
