### ISSUE TITLE
Unexpected token error when blocking domains

### ISSUE THREAD

**Issue by Calbo67** [spatie/browsershot#505]
My browsershot works fine when crawling websites but as soon as I add blockDomains i get unexpected token error.

![image](https://user-images.githubusercontent.com/29214275/116165215-4d5aeb80-a6f3-11eb-999f-734c62c79bb6.png)
![image](https://user-images.githubusercontent.com/29214275/116165267-66fc3300-a6f3-11eb-8f6c-f3062bf1c73e.png)

**Comment by freekmurze** [comment]
I don't have the time to look into this now, but I'd accept a PR that fixes this.

**Comment by Calbo67** [comment]
@freekmurze Any idea what it could possibly be to point me in right direction not sure if its an issue on my end or the code? Its taking too long to crawl since its loading external urls would be very much appreciated if you could help. 
npm version is 6.14.8
node version is 14.15.0
