### ISSUE TITLE
A blank image is generated

### ISSUE THREAD

**Issue by murrion** [spatie/browsershot#6]
Hi. Im using Browsershot in a loop, it works for 2 or 3 URLs but returns a blank image for the others.

I thought it might be that PhantomJS doesn't have enough time to complete its work, so I changed the 5 seconds parameter with no change.

I also read that page.close() might help PhantomJS to clean up after itself but no change with that either.

Have you ever come across this behavior before?

**Comment by freekmurze** [comment]
I've came across that issue before and my solution was to give PhantomJS 5 seconds time to process the page instead of two.

Is the page you are trying to process free of javascript errors?

**Comment by murrion** [comment]
PhantomJS was already set to 5 seconds, I changed it to 10 seconds and above with no change.

I tried Browsershot outside of a loop on specific URLs 1 at a time and it generated black images. 

I don't know if the sites had JS errors. One of the screenshots I was trying to generate which turned out black was my own Github account homepage and there are no JS errors there.

**Comment by freekmurze** [comment]
I'll try to look into it soon

**Comment by martendej** [comment]
@murrion Does the site you want to get a screenshot of use SSL? I had the same problem, I got blank images when trying to get a screenshot of a site with SSL on SNI. If so, check my pull request #11

**Comment by murrion** [comment]
Hi @martendej, I haven't used it in a while so I don't remember, but I don't think I was using it for any HTTPS enabled sites as I was only testing it out.

**Comment by xero88** [comment]
I get the same blank image, is there a way to resolve dat ?
