### ISSUE TITLE
Broken browsershots.org ?

### ISSUE THREAD

**Issue by petterreinholdtsen** [spatie/browsershot#618]
Hi

The browsershots.org web site seem to be broken.  I get a 500 error when trying to submit a url to test it, I get a 500 error from the captcha image on the contact page when trying to give feedback, and there is links to stocks sites in the top menu row.  In addition the set of factories is said to be zero.  In sum it give the impression that the site is no longer operational and is taken over by someone using it only for marketing and linking to unrelated sites.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by freekmurze** [comment]
We don't not run that website.

**Comment by petterreinholdtsen** [comment]
[Freek Van der Herten]
> We don't not run that website.

Aha.  Then <URL: https://www.topbestalternatives.com/browsershots/ > got
it wrong.  Which website do you run?

-- 
Happy hacking
Petter Reinholdtsen
