### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by MJBrennan** [spatie/browsershot#64]
Tested this on Windows and got this error:
 Fatal error: Uncaught Spatie\Browsershot\Exceptions\CouldNotTakeBrowsershot: The current operating system `WINNT` is not supported in C:\xampp\htdocs\ImageCapture\vendor\spatie\browsershot\src\Exceptions\CouldNotTakeBrowsershot.php on line 12

**Comment by freekmurze** [comment]
Like stated in the readme, this package currently only supports Ubuntu 16.04 and MacOS.
