### ISSUE TITLE
Fatal error: Call to undefined method Spatie\Browsershot\Browsershot::url() 

### ISSUE THREAD

**Issue by peshmerge** [spatie/browsershot#65]
Hello Freek,

I want to use the browsershot on scotchbox (Free Version 3.0) vagrant. I have a simple php file :
`   

        require __DIR__ .'/vendor/autoload.php';
        use Spatie\Browsershot\Browsershot;
        $pathToImage = __DIR__."/google.png";
        Browsershot::url('https://google.com')
            ->save($pathToImage);`

My scotch box has the following specs:
Ubuntu 14.04.5 LTS (Trusty Tahr)
  Apache 2.4
  PHP 7

When I run the code I got the following error:
`Fatal error: Call to undefined method Spatie\Browsershot\Browsershot::url() in /var/www/public/spatie-shot/index.php on line 5`

Thanks,
Peshmerge

**Comment by freekmurze** [comment]
The static `url` method definitely exists on `Spatie\Browsershot\Browsershot`:
https://github.com/spatie/browsershot/blob/3f33240/src/Browsershot.php#L29-L32

Are you sure you're using `v2`?

**Comment by peshmerge** [comment]
I have checked my composer.json and this is what I have :/
`{
    "require": {
        "spatie/browsershot": "^1.9"
    }
}
`

**Comment by freekmurze** [comment]
Probably Composer chooses `v1` because you do not meet the requirement for running `v2`.

Are you using PHP 7 on your cli (cli might run a different version then the PHP you use to handle web requests).

**Comment by freekmurze** [comment]
You could try to manually setting the required version to `^2.0` in `composer.json` and then run `composer update`. Maybe composer will spit out a helpful message.

**Comment by peshmerge** [comment]
Thanks Freek :)
PHP7 was the problem. I have reconfigured my ScotchBox and it works fine. 
Here is the first result:
![spatie](https://user-images.githubusercontent.com/531558/27805600-f205eba2-6035-11e7-96ad-38a8e686a21a.png)

This issue can be closed :)

**Comment by freekmurze** [comment]
Nice, glad you found the solution. Have fun taking browsershots!
