### ISSUE TITLE
This repo will be working on centOS 6.7?

### ISSUE THREAD

**Issue by Barmunksu** [spatie/browsershot#68]

**Comment by freekmurze** [comment]
No idea :) test it out, and report back here

**Comment by pithyone** [comment]
It work well on my CentOS.

Server Info：
OS：CentOS Linux 7.4.1708 (Core)　　

If it does not work for you, please refer to [here](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md).
