### ISSUE TITLE
Error: could not create screenshot

### ISSUE THREAD

**Issue by hardikaecor** [spatie/browsershot#7]
I have installed package and tried your example but its giving me following error on vendor/spatie/browsershot/src/Spatie/Browsershot/Browsershot.php on line 160

Exception

could not create screenshot 

Am I missing any step of installation?

Thanks

**Comment by freekmurze** [comment]
The underlying component, PhantomJS, sometimes has trouble rendering javascript heavy sites. 
Could you try to make a screenshot of a simple site (eg. google.com) and see if that works?

**Comment by hardikaecor** [comment]
Thanks for the reply but it still doesn't work. Do i need to give any permissions of install something else?
I am using mac osx

**Comment by hardikaecor** [comment]
this worked when i downloaded the phantomjs binary for mac osx and replaced urs with it.
so i think its just the issue of OS specific binaries.

**Comment by freekmurze** [comment]
The binary included is intended for Linux. Maybe it's possible for me to include the osx binary as well and detect when that one should be used. I'll investigate this in the coming weeks.

**Comment by paulalexandru** [comment]
I have the same error, I tryed with google.com also but I still get the same error "could not create screenshot". But even if this worked, it was useful since it does not work on any website...

**Comment by shivergard** [comment]
same issue...

**Comment by hardikaecor** [comment]
I got the solution by changing the binary of Phantomjs from Linux to mac osx.
You can try to do that, I will try to add the pull request for loading OS specific binaries when i get free this weekend.

**Comment by efusionsoft** [comment]
@hardikaecor did you mean you changed the binary on your mac machine? Question is how would I make it work on the Linux, checked the phantomjs website and they say that the library is not yet available for the Linux OS.

**Comment by freekmurze** [comment]
I've added a note to the readme that the included bin requires a specific OS.

**Comment by patelchirag123** [comment]
In Windows os , below error is come so any one know how to solve it 
i pass simple google.com url but still i get this error so plz replay me 
Error:


Exception 
could not create screenshot

**Comment by freekmurze** [comment]
The package only included a binary that runs on Ubuntu. Windows is not supported.

**Comment by Scottzozer** [comment]
I do not see the added information in the README.md file. I had to load my own phantomjs binary to get this working on my mac. Will see if the included works on my linux ubuntu 14.04 later on.

**Comment by PeterTiriwo** [comment]
I am having the same problem in linux
Exception in Browsershot.php line 254: could not create screenshot

**Comment by sohailglt** [comment]
> The package only included a binary that runs on Ubuntu
yes the package is supported on ubuntu.. I have developed the app on ubuntu but now i have installed vestacp on my server and shifted app to vestacp. 

What is solution?
