### ISSUE TITLE
Delay capturing process

### ISSUE THREAD

**Issue by Kuuseorg** [spatie/browsershot#76]
Hello!

Thank you for this repository!

Is there a chance to delay the process of image capturing? Let's say I have pages that have animations and image is captured before the content animations have finished off. Is it even possible in theory?

Best,
Priit

**Comment by freekmurze** [comment]
Unfortunately Chrome does not support a delay yet. Though there's no official info on it my guess is that such an option will be introduced in some future version of Chrome.

**Comment by njbarrett** [comment]
I thought this was possible with `$browsershot->setTimeout(10000)` ?

**Comment by clarkwinkelmann** [comment]
This is sad... I wanted to render javascript-only pages to images but the screenshot only reads "loading" (that's the only content on the page without JS) :sweat_smile: 

I've seen node libraries that used delays or even page events to trigger the screenshot, but I believe they connect to the debug port of chrome to interact with the headless browser ?

**Comment by freekmurze** [comment]
If you feel you can improve the package, send a PR.
