### ISSUE TITLE
Support specifying DevTools options

### ISSUE THREAD

**Issue by hackel** [spatie/browsershot#78]
It would be great if there was a way to specify options for a capture, using the DevTools protocol.

See: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF

This would require spawning the Chromium process and connecting to it over a socket connection, instead of just using the --print-to-pdf option.

I'm going to play around with this a little bit and could possibly create a PR if I manage to get anywhere.

**Comment by freekmurze** [comment]
Sounds good. Closing this issue for now, we'll continue the conversation on the future PR.

**Comment by barryvdh** [comment]
Not sure if you already saw this, but there is a Mink driver for example, using this: https://gitlab.com/DMore/chrome-mink-driver

Should have a good example and tested code of how to use the Devtools API

**Comment by freekmurze** [comment]
@barryvdh Seems awesome, thanks. Will dive into it when I got some time.
