### ISSUE TITLE
Retina/HDPI Support

### ISSUE THREAD

**Issue by mikepostma** [spatie/browsershot#79]
@freekmurze First of all, great package, very easy to get up and running and delivers by far the most accurate screenshots. I'm wondering if you would be open to adding support for retina quality screenshots to the package? All it would really involve is adding an optional `--force-device-scale-factor` parameter to both create commands.

I don't mind putting together a pull-request but I figured I'd check to see if you'd even be interested first / would just rather add this yourself since it's such a small change. Also, if you wish to give any direction on naming variables / functions, please do. I think the most flexible option is something like:

```
if ($this->deviceScaleFactor != 1) {
  $command .= ' --force-device-scale-factor='.$this->deviceScaleFactor;
}
```

Where acceptable values would be 1, 2 or 3. What do you think?

**Comment by freekmurze** [comment]
Seems nice to have it in the package, please do send a PR

**Comment by mikepostma** [comment]
Ok, I'll try to put something together over the weekend

**Comment by mikepostma** [comment]
Got swamped that weekend, but better late than never! See #81

**Comment by freekmurze** [comment]
Thanks, we'll handle it further in #81
