### ISSUE TITLE
Login before taking screenshot

### ISSUE THREAD

**Issue by antton** [spatie/browsershot#88]
Hi your project looks very interesting but I would like to know how can I login before taking the screenshot.

Did your code have any function or way to do it?

Thanks for all!

**Comment by lukesnowden** [comment]
#29 may help?

**Comment by antton** [comment]
I don't get it how to pass a login form protected with sessionkey with that example :(

**Comment by lukesnowden** [comment]
Are you using Laravel or some other framework?

**Comment by antton** [comment]
Hi @lukesnowden 

No I'm not using any framework but I'll try to check how to make the login part.
If you tell me that is possible it is enough.

Thanks

**Comment by freekmurze** [comment]
You could append some sort of signature to your url. You app should show the page when a valid signature is present. You could use this package to achieve it: https://github.com/spatie/laravel-url-signer
