### ISSUE TITLE
Default value for parameters with a class type hint can only be NULL in Browsershot.php (line 51)

### ISSUE THREAD

**Issue by umairali** [spatie/browsershot#97]
i m trying to save image or pdf but i m receiving this error

```
Default value for parameters with a class type hint can only be NULL
--
in Browsershot.php (line 51)
```

**Comment by freekmurze** [comment]
Which version of Brosershot are you using? How can we recreate the problem? Could you PR a failing test?

**Comment by ami-m** [comment]
happens to me too. version 3.12.0

I reproduced it with this sample code

`<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use AppBundle\PdfGenerator\SpatiePdfGenerator;


class TestController extends Controller
{

    /**
    * @Route("/test")
    */
    public function testAction(SpatiePdfGenerator $generator)
    {
      $generator->createPdfFileFromHtml("hello world");
      return new Response("ok");
    }
}
`

**Comment by freekmurze** [comment]
@ami-m Could you upgrade to the latests version and check if the problem is present in that version?

**Comment by ami-m** [comment]
no need.
turns out the virtual machine I tested it on was using php5.6
an upgrade to 7.2 fixed it.

sorry for bothering.
